#!/usr/bin/env python3
"""img2c.py — bake an image into a small embedded RGBA C header for carcal.

    python3 tools/img2c.py PHOTO.jpg [width] [out.h]

Downscales PHOTO to `width` px (default 100, keeping aspect) and writes
`out.h` (default src/about_image.h) containing:

    #define ABOUT_IMG_W <w>
    #define ABOUT_IMG_H <h>
    static const unsigned char about_img_rgba[...] = { ... };  // R,G,B,A order

carcal's About window renders this buffer with libcaca's caca_dither_bitmap,
so nothing is loaded from disk at runtime.
"""
import sys
from PIL import Image


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    src = sys.argv[1]
    width = int(sys.argv[2]) if len(sys.argv) > 2 else 100
    out = sys.argv[3] if len(sys.argv) > 3 else "src/about_image.h"

    im = Image.open(src).convert("RGBA")
    w0, h0 = im.size
    height = max(1, round(width * h0 / w0))
    im = im.resize((width, height), Image.LANCZOS)
    data = im.tobytes()  # RGBA, row-major

    with open(out, "w") as f:
        f.write("/* Generated by tools/img2c.py from %s — do not edit.\n"
                " * Embedded RGBA pixels (bytes in R,G,B,A order). */\n" % src)
        f.write("#ifndef CARCAL_ABOUT_IMAGE_H\n#define CARCAL_ABOUT_IMAGE_H\n\n")
        f.write("#define ABOUT_IMG_W %d\n#define ABOUT_IMG_H %d\n\n" % (width, height))
        f.write("static const unsigned char about_img_rgba[ABOUT_IMG_W * ABOUT_IMG_H * 4] = {\n")
        for i in range(0, len(data), 20):
            f.write("  " + ",".join("%d" % b for b in data[i:i + 20]) + ",\n")
        f.write("};\n\n#endif /* CARCAL_ABOUT_IMAGE_H */\n")
    print("wrote %s (%dx%d, %d bytes embedded)" % (out, width, height, len(data)))


if __name__ == "__main__":
    main()
