/*
 * caracal — a terminal packet analyzer (a tiny Wireshark for the TUI).
 *
 *   caracal [capture.pcap|.pcapng]
 *
 * Layout:  [menu bar] / [display-filter entry] / [packet table] /
 *          [packet-detail tree] / [status bar]
 *
 * Built on gtcaca's lazy Table and Tree widgets and libpcapng for reading
 * pcapng. Custom protocols are added at runtime by loading .posa definitions
 * (File ▸ Load .posa) and binding them to ports (Analyze ▸ Decode As…).
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <sys/stat.h>

#include <caca.h>

#include <gtcaca/main.h>
#include <gtcaca/application.h>
#include <gtcaca/window.h>
#include <gtcaca/menu.h>
#include <gtcaca/table.h>
#include <gtcaca/tree.h>
#include <gtcaca/entry.h>
#include <gtcaca/label.h>
#include <gtcaca/checkbox.h>
#include <gtcaca/radiobutton.h>
#include <gtcaca/button.h>
#include <gtcaca/progressbar.h>
#include <gtcaca/statusbar.h>
#include <gtcaca/dialog.h>
#include <gtcaca/filechooser.h>
#include <gtcaca/image.h>
#include <gtcaca/textview.h>
#include <gtcaca/editor.h>
#include <gtcaca/linechart.h>
#include <gtcaca/hexview.h>
#include <gtcaca/tree.h>
#include <gtcaca/gauge.h>

#include <libpcapng/reassembly_tcp.h>   /* pcapng_tcp_reasm_* for Follow TCP Stream */

#include "caracal.h"
#include "about_image.h"   /* embedded caracal photo (generated by tools/img2c.py) */

#ifndef CARACAL_PROTOS_DIR
#define CARACAL_PROTOS_DIR "protos"
#endif
#ifndef CARACAL_GRAMMARS_DIR
#define CARACAL_GRAMMARS_DIR "grammars"
#endif

#define CTRL(c) ((c) & 0x1f)

/* Data directories: env override (set by a relocatable bundle's launcher) wins
   over the compile-time default. */
static const char *protos_dir(void)
{ const char *e = getenv("CARACAL_PROTOS_DIR"); return (e && *e) ? e : CARACAL_PROTOS_DIR; }
static const char *grammars_dir(void)
{ const char *e = getenv("CARACAL_GRAMMARS_DIR"); return (e && *e) ? e : CARACAL_GRAMMARS_DIR; }

enum { FOCUS_FILTER = 0, FOCUS_TABLE, FOCUS_TREE, FOCUS_HEX, FOCUS_COUNT };

typedef struct {
  capture_t cap;

  long     *view;        /* indices into cap.pkts that pass the filter        */
  long      nview;
  long      view_cap;
  cfilter_t *filter;
  char      filter_text[256];

  cfield_t *detail_root; /* dissection of the currently selected packet       */
  long      detail_for;  /* view row the detail belongs to (-1 = none)        */

  int       focus;

  /* widgets */
  gtcaca_menu_widget_t      *menu;
  gtcaca_entry_widget_t     *fentry;
  gtcaca_table_widget_t     *table;
  gtcaca_tree_widget_t      *tree;
  gtcaca_hexview_widget_t   *hex;     /* byte pane for the selected packet */
  gtcaca_gauge_widget_t     *matchbar;/* filter-match ratio gauge          */
  gtcaca_statusbar_widget_t *bar;

  /* find-packet state */
  uint8_t  find_bytes[256];
  int      find_len;
  char     find_str[256];
  int      find_is_hex;
  int      find_nocase;     /* case-insensitive search */
  int      find_active;

  /* layout (for mouse hit-testing) */
  int table_y, table_h, tree_y, tree_h, tree_w;
  int show_tree, show_hex;   /* View menu: show/hide the detail panes */
} app_t;

static app_t app;
static int   g_quit = 0;   /* set by File > Quit; the event loop checks it */

/* ───────────────────────── view (filtered index list) ─────────────────── */
static void view_push(long idx)
{
  if (app.nview == app.view_cap) {
    long nc = app.view_cap ? app.view_cap * 2 : 1024;
    long *nv = realloc(app.view, (size_t)nc * sizeof *nv);
    if (!nv) return;
    app.view = nv;
    app.view_cap = nc;
  }
  app.view[app.nview++] = idx;
}

static long view_pkt_index(long row)   /* table row → cap.pkts index */
{
  if (row < 0 || row >= app.nview) return -1;
  return app.view[row];
}

static void view_rebuild(void)
{
  long i;
  app.nview = 0;
  for (i = 0; i < app.cap.count; i++) {
    cfield_t *root;
    int pass;
    if (app.filter == NULL) { view_push(i); continue; }
    root = dissect_packet(&app.cap.pkts[i]);
    pass = filter_eval(app.filter, root);
    cfield_free(root);
    if (pass) view_push(i);
  }
}

static void invalidate_summaries(void)
{
  long i;
  for (i = 0; i < app.cap.count; i++) app.cap.pkts[i].summarized = 0;
}

/* ───────────────────────── detail tree (re)build ──────────────────────── */
static void detail_clear(void)
{
  if (app.detail_root) { cfield_free(app.detail_root); app.detail_root = NULL; }
  app.detail_for = -1;
}

static gtcaca_tree_model_t tree_model;   /* defined below */

/* Point the hex byte pane at the selected packet's bytes. */
static void hex_fill(const cpkt_t *p)
{
  char t[40];
  if (!app.hex) return;
  if (p) {
    gtcaca_hexview_set_data(app.hex, p->data, (int)p->caplen);
    snprintf(t, sizeof t, "Bytes (%u)", p->caplen);
    gtcaca_hexview_set_title(app.hex, t);
  } else {
    gtcaca_hexview_set_data(app.hex, NULL, 0);
    gtcaca_hexview_set_title(app.hex, "Bytes");
  }
  gtcaca_hexview_set_highlight(app.hex, -1, 0);
}

/* Highlight, in the hex pane, the bytes of the field selected in the tree
   (climbing to the nearest ancestor that carries a byte range). */
static void hex_sync_highlight(void)
{
  cfield_t *n;
  if (!app.hex || !app.tree) return;
  n = (cfield_t *)gtcaca_tree_selected_node(app.tree);
  while (n && n->len <= 0) n = n->parent;
  if (n && n->len > 0) gtcaca_hexview_set_highlight(app.hex, n->off, n->len);
  else                 gtcaca_hexview_set_highlight(app.hex, -1, 0);
}

static void detail_rebuild(long row)
{
  long pidx = view_pkt_index(row);
  detail_clear();
  if (pidx >= 0)
    app.detail_root = dissect_packet(&app.cap.pkts[pidx]);
  app.detail_for = row;
  /* Re-set the model so the tree's expand-state is rebuilt against the new
     node pointers (set_model frees the old open-state). */
  if (app.tree) gtcaca_tree_set_model(app.tree, &tree_model);
  hex_fill(pidx >= 0 ? &app.cap.pkts[pidx] : NULL);
}

/* ───────────────────────── table model ────────────────────────────────── */
static long tm_rows(gtcaca_table_model_t *m) { (void)m; return app.nview; }
static int  tm_cols(gtcaca_table_model_t *m) { (void)m; return 7; }

static void tm_header(gtcaca_table_model_t *m, int col, char *b, int l)
{
  static const char *h[] = { "No.", "Time", "Source", "Destination",
                             "Protocol", "Length", "Info" };
  (void)m;
  snprintf(b, l, "%s", (col >= 0 && col < 7) ? h[col] : "");
}

static void tm_cell(gtcaca_table_model_t *m, long row, int col, char *b, int l)
{
  long pidx = view_pkt_index(row);
  cpkt_t *p;
  (void)m;
  if (pidx < 0) { b[0] = '\0'; return; }
  p = &app.cap.pkts[pidx];
  dissect_summarize(p);
  switch (col) {
  case 0: snprintf(b, l, "%ld", pidx + 1); break;
  case 1: {
    double t = (double)((p->ts_us >= app.cap.first_ts_us)
                          ? p->ts_us - app.cap.first_ts_us : 0) / 1e6;
    snprintf(b, l, "%.6f", t);
    break;
  }
  case 2: snprintf(b, l, "%s", p->col_src); break;
  case 3: snprintf(b, l, "%s", p->col_dst); break;
  case 4: snprintf(b, l, "%s", p->col_proto); break;
  case 5: snprintf(b, l, "%u", p->origlen); break;
  case 6: snprintf(b, l, "%s", p->col_info); break;
  default: b[0] = '\0';
  }
}

static gtcaca_table_model_t table_model = { tm_rows, tm_cols, tm_header, tm_cell, NULL };

/* ───────────────────────── tree model ─────────────────────────────────── */
/* Nodes are cfield_t*. The super-root (NULL) maps to detail_root's children. */
static cfield_t *tree_parent(void *node) { return node ? (cfield_t *)node : app.detail_root; }

static long tn_child_count(gtcaca_tree_model_t *m, void *node)
{ (void)m; return cfield_count(tree_parent(node)); }

static void *tn_child(gtcaca_tree_model_t *m, void *node, long i)
{ (void)m; return cfield_child_at(tree_parent(node), (int)i); }

static void tn_label(gtcaca_tree_model_t *m, void *node, char *b, int l)
{
  cfield_t *f = (cfield_t *)node;
  (void)m;
  if (!f) { b[0] = '\0'; return; }
  if (f->label[0]) snprintf(b, l, "%s", f->label);
  else             snprintf(b, l, "%s", f->abbrev);
}

static int tn_has_children(gtcaca_tree_model_t *m, void *node)
{ (void)m; return cfield_count((cfield_t *)node) > 0; }

static gtcaca_tree_model_t tree_model = {
  tn_child_count, tn_child, tn_label, tn_has_children, NULL, NULL /* draw_row */
};

/* ───────────────────────── status line ────────────────────────────────── */
static void refresh_status(void)
{
  char s[320];
  const char *focusname = app.focus == FOCUS_FILTER ? "filter"
                        : app.focus == FOCUS_TABLE  ? "table"
                        : app.focus == FOCUS_TREE   ? "tree" : "hex";
  if (app.cap.count == 0) {
    snprintf(s, sizeof s, " No capture  |  F2 Open  F10 Menu  Tab switch  ^Q quit");
  } else {
    long sel = app.table ? gtcaca_table_selected_row(app.table) : 0;
    snprintf(s, sizeof s,
      " %s  |  %ld/%ld pkts shown  |  sel %ld  |  [%s]  |  / filter  F2 open  F10 menu  ^Q quit",
      app.cap.path[0] ? app.cap.path : "(none)",
      app.nview, app.cap.count, app.nview ? sel + 1 : 0, focusname);
  }
  gtcaca_statusbar_set_text(app.bar, s);
}

/* ───────────────────────── filter handling ────────────────────────────── */
static void apply_filter(const char *expr)
{
  char err[160] = "";
  cfilter_t *nf = filter_compile(expr, err, sizeof err);
  if (!nf) {
    gtcaca_dialog_message("Filter error", err[0] ? err : "invalid display filter");
    return;
  }
  if (app.filter) filter_free(app.filter);
  app.filter = nf;
  snprintf(app.filter_text, sizeof app.filter_text, "%s", expr ? expr : "");
  view_rebuild();
  if (app.table) gtcaca_table_set_current(app.table, 0, 0);
  detail_rebuild(0);
}

/* ───────────────────────── capture loading ────────────────────────────── */
/* progress callback driving the load gauge (throttled to ~2% steps) */
static double g_loadlast;
static void loadbar_cb(void *ud, double frac)
{
  gtcaca_gauge_widget_t *g = ud;
  if (frac < g_loadlast + 0.02 && frac < 1.0) return;
  g_loadlast = frac;
  gtcaca_gauge_set_value(g, (float)frac);
  gtcaca_redraw();
}

static void load_capture(const char *path)
{
  capture_t nc;
  char err[256] = "";
  int rc;
  struct stat st;
  gtcaca_window_widget_t *lwin = NULL;
  gtcaca_gauge_widget_t  *lg = NULL;

  /* For a sizeable file, show a modal load-progress gauge. */
  if (gmo.cv && stat(path, &st) == 0 && st.st_size > (1 << 20)) {
    int W = caca_get_canvas_width(gmo.cv), w = 46;
    if (w > W - 2) w = W - 2;
    lwin = gtcaca_window_new_centered(NULL, "Loading capture", w, 5);
    lg   = gtcaca_gauge_new(GTCACA_WIDGET(lwin), 2, 2, w - 4);
    gtcaca_gauge_set_colors(lg, CACA_GREEN, CACA_BLUE);
    g_loadlast = -1.0;
    capture_set_progress(loadbar_cb, lg);
  }

  rc = capture_load(path, &nc, err, sizeof err);

  if (lg) {
    capture_set_progress(NULL, NULL);
    CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(lg));   gtcaca_gauge_free(lg);
    CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(lwin)); free(lwin);
  }

  if (rc != 0) {
    gtcaca_dialog_message("Open failed", err[0] ? err : "could not read file");
    return;
  }
  capture_free(&app.cap);
  app.cap = nc;
  view_rebuild();
  if (app.table) {
    gtcaca_table_set_title(app.table, app.cap.path);
    gtcaca_table_set_current(app.table, 0, 0);
  }
  detail_rebuild(0);
}

/* ───────────────────────── one-line modal prompt ──────────────────────── */
static int prompt_line(const char *label, char *out, int outlen)
{
  int W = caca_get_canvas_width(gmo.cv), H = caca_get_canvas_height(gmo.cv);
  int len = 0;
  caca_event_t ev;
  out[0] = '\0';
  for (;;) {
    int x;
    caca_set_color_ansi(gmo.cv, CACA_BLACK, CACA_WHITE);
    for (x = 0; x < W; x++) caca_put_char(gmo.cv, x, H - 1, ' ');
    caca_printf(gmo.cv, 0, H - 1, "%s%s", label, out);
    caca_refresh_display(gmo.dp);
    if (!caca_get_event(gmo.dp, CACA_EVENT_KEY_PRESS, &ev, -1)) continue;
    {
      int k = caca_get_event_key_ch(&ev);
      if (k == CACA_KEY_RETURN || k == 10) return len > 0;
      if (k == CACA_KEY_ESCAPE) return 0;
      if ((k == CACA_KEY_BACKSPACE || k == CACA_KEY_DELETE) && len > 0) out[--len] = '\0';
      else if (k >= 32 && k < 127 && len < outlen - 1) { out[len++] = (char)k; out[len] = '\0'; }
    }
  }
}

/* ───────────────────────── find packet (string / hex) ─────────────────── */
static const uint8_t *mem_find(const uint8_t *hay, int hlen, const uint8_t *need, int nlen)
{
  int i;
  if (nlen <= 0 || nlen > hlen) return NULL;
  for (i = 0; i <= hlen - nlen; i++)
    if (memcmp(hay + i, need, (size_t)nlen) == 0) return hay + i;
  return NULL;
}

/* case-insensitive byte search (ASCII letters folded) */
static const uint8_t *ci_mem_find(const uint8_t *hay, int hlen, const uint8_t *need, int nlen)
{
  int i, j;
  if (nlen <= 0 || nlen > hlen) return NULL;
  for (i = 0; i <= hlen - nlen; i++) {
    for (j = 0; j < nlen; j++)
      if (tolower(hay[i + j]) != tolower(need[j])) break;
    if (j == nlen) return hay + i;
  }
  return NULL;
}

static int hexparse(const char *s, uint8_t *out, int max)
{
  int n = 0;
  while (*s) {
    int hi, lo;
    while (*s == ' ' || *s == ':' || *s == ',') s++;
    if (!*s) break;
    if (!isxdigit((unsigned char)s[0]) || !isxdigit((unsigned char)s[1])) return -1;
    if (n >= max) return -1;
    hi = isdigit((unsigned char)s[0]) ? s[0] - '0' : (tolower(s[0]) - 'a' + 10);
    lo = isdigit((unsigned char)s[1]) ? s[1] - '0' : (tolower(s[1]) - 'a' + 10);
    out[n++] = (uint8_t)((hi << 4) | lo);
    s += 2;
  }
  return n;
}

static int ci_contains(const char *hay, const char *needle)
{
  size_t nl = strlen(needle), i;
  if (!nl) return 1;
  for (i = 0; hay[i]; i++) {
    size_t j = 0;
    while (needle[j] && hay[i + j] &&
           tolower((unsigned char)hay[i + j]) == tolower((unsigned char)needle[j])) j++;
    if (!needle[j]) return 1;
  }
  return 0;
}

/* does packet at cap index match the active find term? */
static int pkt_find_match(long pidx)
{
  cpkt_t *p = &app.cap.pkts[pidx];
  if (app.find_len > 0) {
    const uint8_t *hit = app.find_nocase
      ? ci_mem_find(p->data, (int)p->caplen, app.find_bytes, app.find_len)
      : mem_find(p->data, (int)p->caplen, app.find_bytes, app.find_len);
    if (hit) return 1;
  }
  if (!app.find_is_hex && app.find_str[0]) {        /* text also matches columns */
    dissect_summarize(p);
    if (app.find_nocase)
      return ci_contains(p->col_info, app.find_str) || ci_contains(p->col_src, app.find_str) ||
             ci_contains(p->col_dst, app.find_str)  || ci_contains(p->col_proto, app.find_str);
    return strstr(p->col_info, app.find_str) || strstr(p->col_src, app.find_str) ||
           strstr(p->col_dst, app.find_str)  || strstr(p->col_proto, app.find_str);
  }
  return 0;
}

/* jump to the next/prev matching row (dir = +1 / -1), wrapping. */
static int find_jump(int dir)
{
  long i, cur;
  if (!app.find_active || app.nview == 0) return 0;
  cur = app.table ? gtcaca_table_selected_row(app.table) : 0;
  for (i = 1; i <= app.nview; i++) {
    long row = (cur + dir * i) % app.nview;
    if (row < 0) row += app.nview;
    if (pkt_find_match(view_pkt_index(row))) {
      gtcaca_table_set_current(app.table, row, 0);
      detail_rebuild(row);
      return 1;
    }
  }
  return 0;
}

/* Modal Find dialog: text entry, String/Hex radios, Case-sensitive and
   Search-backwards checkboxes, and Find/Cancel buttons. */
static void act_find(void *u)
{
  int W = caca_get_canvas_width(gmo.cv), H = caca_get_canvas_height(gmo.cv);
  int w = 54, h = 12, f = 0, result = 0, i, hexerr = 0, back = 0;
  gtcaca_window_widget_t *win;
  gtcaca_label_widget_t *lbl;
  gtcaca_entry_widget_t *ent;
  gtcaca_radiobutton_widget_t *rbs, *rbh;
  gtcaca_checkbox_widget_t *cbcase, *cbback;
  gtcaca_button_widget_t *bfind, *bcancel;
  gtcaca_widget_t *ring[7];
  caca_event_t ev;
  (void)u;

  if (w > W - 2) w = W - 2;
  if (h > H - 2) h = H - 2;
  win    = gtcaca_window_new_centered(NULL, "Find Packet", w, h);
  lbl    = gtcaca_label_new(GTCACA_WIDGET(win), "Find:", 2, 1);
  ent    = gtcaca_entry_new(GTCACA_WIDGET(win), 8, 1, w - 10);
  if (app.find_str[0]) gtcaca_entry_set_text(ent, app.find_str);
  rbs    = gtcaca_radiobutton_new(GTCACA_WIDGET(win), "String",     1, 3, 3);
  rbh    = gtcaca_radiobutton_new(GTCACA_WIDGET(win), "Hex value",  1, 18, 3);
  if (app.find_is_hex) gtcaca_radiobutton_set_active(rbh);
  else                 gtcaca_radiobutton_set_active(rbs);
  cbcase = gtcaca_checkbox_new(GTCACA_WIDGET(win), "Case sensitive",   2, 5);
  cbback = gtcaca_checkbox_new(GTCACA_WIDGET(win), "Search backwards", 2, 6);
  if (app.find_active && !app.find_nocase) gtcaca_checkbox_set_checked(cbcase, 1);
  bfind   = gtcaca_button_new(GTCACA_WIDGET(win), "Find",   2, 8);
  bcancel = gtcaca_button_new(GTCACA_WIDGET(win), "Cancel", 12, 8);
  (void)lbl;

  ring[0] = GTCACA_WIDGET(ent);  ring[1] = GTCACA_WIDGET(rbs);  ring[2] = GTCACA_WIDGET(rbh);
  ring[3] = GTCACA_WIDGET(cbcase); ring[4] = GTCACA_WIDGET(cbback);
  ring[5] = GTCACA_WIDGET(bfind);  ring[6] = GTCACA_WIDGET(bcancel);

  while (result == 0) {
    int k;
    for (i = 0; i < 7; i++) ring[i]->has_focus = (i == f);
    gtcaca_redraw();
    if (!caca_get_event(gmo.dp, CACA_EVENT_KEY_PRESS, &ev, -1)) continue;
    k = caca_get_event_key_ch(&ev);
    if (k == CACA_KEY_ESCAPE) { result = 2; break; }
    if (k == '\t' || k == CACA_KEY_DOWN) { f = (f + 1) % 7; continue; }
    if (k == CACA_KEY_UP)                { f = (f + 6) % 7; continue; }
    if (k == CACA_KEY_RETURN || k == 10) { result = (ring[f] == GTCACA_WIDGET(bcancel)) ? 2 : 1; break; }
    if (ring[f] == GTCACA_WIDGET(ent)) { ent->private_key_cb(ent, k, NULL); continue; }
    if (k == ' ') {
      if      (ring[f] == GTCACA_WIDGET(rbs)) gtcaca_radiobutton_set_active(rbs);
      else if (ring[f] == GTCACA_WIDGET(rbh)) gtcaca_radiobutton_set_active(rbh);
      else if (ring[f] == GTCACA_WIDGET(cbcase)) gtcaca_checkbox_set_checked(cbcase, !gtcaca_checkbox_get_checked(cbcase));
      else if (ring[f] == GTCACA_WIDGET(cbback)) gtcaca_checkbox_set_checked(cbback, !gtcaca_checkbox_get_checked(cbback));
    }
  }

  if (result == 1) {
    const char *txt = gtcaca_entry_get_text(ent);
    int hex = gtcaca_radiobutton_get_active(rbh);
    back = gtcaca_checkbox_get_checked(cbback);
    if (hex) {
      int n = hexparse(txt, app.find_bytes, (int)sizeof app.find_bytes);
      if (n <= 0) hexerr = 1;
      else { app.find_len = n; app.find_is_hex = 1; app.find_str[0] = '\0'; }
    } else {
      int n = (int)strlen(txt);
      if (n > (int)sizeof app.find_bytes) n = (int)sizeof app.find_bytes;
      memcpy(app.find_bytes, txt, (size_t)n);
      app.find_len = n; app.find_is_hex = 0;
      snprintf(app.find_str, sizeof app.find_str, "%s", txt);
    }
    app.find_nocase = !gtcaca_checkbox_get_checked(cbcase);
    if (!hexerr) app.find_active = (app.find_len > 0);
  }

  /* teardown */
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(bcancel)); free(bcancel);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(bfind));   free(bfind);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(cbback));  free(cbback);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(cbcase));  free(cbcase);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(rbh));     free(rbh);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(rbs));     free(rbs);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(ent));     free(ent);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(lbl));     free(lbl);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(win));     free(win);
  if (app.menu) { app.menu->is_open = 0; app.menu->has_focus = 0; }

  if (hexerr) { gtcaca_dialog_message("Find", "Invalid hex bytes."); return; }
  if (result == 1 && app.find_active && !find_jump(back ? -1 : +1))
    gtcaca_dialog_message("Find", "No match.");
}

static void act_find_next(void *u) { (void)u; if (app.find_active) find_jump(+1); }
static void act_find_prev(void *u) { (void)u; if (app.find_active) find_jump(-1); }

/* ───────────────────────── menu actions ───────────────────────────────── */
static void act_open(void *u)
{
  char path[1024];
  (void)u;
  if (gtcaca_filechooser_run(app.cap.path[0] ? "." : ".", path, sizeof path, 0))
    load_capture(path);
}

static void act_reload(void *u)
{
  char path[1024];
  (void)u;
  if (!app.cap.path[0]) return;
  snprintf(path, sizeof path, "%s", app.cap.path);
  load_capture(path);
}

static int confirm_quit(void)
{ return gtcaca_dialog_confirm("Quit caracal", "Are you sure you want to quit?"); }

static void act_quit(void *u) { (void)u; if (confirm_quit()) g_quit = 1; }

static void act_decode_as(void *u)
{
  char line[128], proto[64];
  char transport[16];
  unsigned port;
  (void)u;
  if (posa_count() == 0) {
    gtcaca_dialog_message("Decode As", "No custom protocols loaded.\nUse File \xe2\x96\xb8 Load .posa first.");
    return;
  }
  if (!prompt_line("Decode As (e.g. 'udp 69 TFTP'):  ", line, sizeof line)) return;
  if (sscanf(line, "%15s %u %63s", transport, &port, proto) != 3) {
    gtcaca_dialog_message("Decode As", "Expected: <udp|tcp> <port> <ProtocolName>");
    return;
  }
  if (!posa_find(proto)) {
    /* allow group names too; only warn if neither a proto nor a group */
    int i, isgroup = 0;
    for (i = 0; i < posa_count(); i++)
      if (strcmp(posa_at(i)->parent, proto) == 0) { isgroup = 1; break; }
    if (!isgroup) {
      gtcaca_dialog_message("Decode As", "Unknown protocol name.");
      return;
    }
  }
  if (!strcmp(transport, "udp"))      posa_bind_udp((uint16_t)port, proto);
  else if (!strcmp(transport, "tcp")) posa_bind_tcp((uint16_t)port, proto);
  else { gtcaca_dialog_message("Decode As", "Transport must be 'udp' or 'tcp'."); return; }

  invalidate_summaries();
  view_rebuild();
  detail_rebuild(app.table ? gtcaca_table_selected_row(app.table) : 0);
}

/* About box: render the embedded caracal photo with libcaca (via gtcaca's image
   widget, which dithers an RGBA buffer onto the canvas) plus a short caption.
   The image bytes are compiled in (about_image.h) — nothing is read from disk. */
static void act_about(void *u)
{
  int W = caca_get_canvas_width(gmo.cv), H = caca_get_canvas_height(gmo.cv);
  int w, h, imgh, cols, ix;
  gtcaca_window_widget_t *win;
  gtcaca_image_widget_t *img;
  gtcaca_label_widget_t *l1, *l2, *l3;
  caca_event_t ev;
  (void)u;

  /* Use most of the screen so the dithered photo has enough cells to read. */
  w = W - 8; if (w > 72) w = 72; if (w > W - 2) w = W - 2; if (w < 24) w = 24;
  h = H - 4;               if (h > H - 2) h = H - 2; if (h < 12) h = 12;

  win  = gtcaca_window_new_centered(NULL, "About caracal", w, h);
  imgh = h - 6;            /* rows for the photo; rest for the caption */

  /* Keep the photo's aspect: terminal cells are ~2:1 tall, so the number of
     columns for a given row count is rows * (imgW/imgH) * 2. Centre it. */
  cols = (int)((double)imgh * (double)ABOUT_IMG_W / (double)ABOUT_IMG_H * 2.0 + 0.5);
  if (cols > w - 2) cols = w - 2;
  if (cols < 1) cols = 1;
  ix = (w - cols) / 2; if (ix < 1) ix = 1;

  img = gtcaca_image_new(GTCACA_WIDGET(win), ix, 1, cols, imgh);
  /* Point the widget straight at the embedded RGBA buffer rather than loading a
     file; image_draw() builds a caca_dither from it each frame. */
  img->pixels     = (void *)about_img_rgba;
  img->img_width  = ABOUT_IMG_W;
  img->img_height = ABOUT_IMG_H;

  l1 = gtcaca_label_new(GTCACA_WIDGET(win), "caracal \xe2\x80\x94 a TUI packet analyzer", 2, imgh + 2);
  l2 = gtcaca_label_new(GTCACA_WIDGET(win), "gtcaca + libpcapng + LuaJIT", 2, imgh + 3);
  l3 = gtcaca_label_new(GTCACA_WIDGET(win), "Press any key to close", 2, imgh + 4);

  for (;;) {
    gtcaca_redraw();
    if (!caca_get_event(gmo.dp, CACA_EVENT_KEY_PRESS, &ev, -1)) continue;
    break;
  }

  /* Take the widgets back out of the global draw list, then free. Clear the
     borrowed pixel pointer first so image_free() doesn't free static data. */
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(l3)); free(l3);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(l2)); free(l2);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(l1)); free(l1);
  img->pixels = NULL;
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(img)); gtcaca_image_free(img);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(win)); free(win);

  if (app.menu) { app.menu->is_open = 0; app.menu->has_focus = 0; }
}

/* ───────────────────────── modal windows (follow/graph/decoders/editor) ── */
static gtcaca_window_widget_t *modal_window(const char *title, int *ow, int *oh)
{
  int W = caca_get_canvas_width(gmo.cv), H = caca_get_canvas_height(gmo.cv);
  int w = W - 6, h = H - 4;
  if (w > 130) w = 130;
  if (w < 24) w = 24;
  if (h < 10) h = 10;
  *ow = w; *oh = h;
  return gtcaca_window_new_centered(NULL, (char *)title, w, h);
}

static void modal_close_menu(void)
{ if (app.menu) { app.menu->is_open = 0; app.menu->has_focus = 0; } }

/* scroll a textview until Esc/q */
static void modal_scroll_loop(gtcaca_textview_widget_t *tv)
{
  caca_event_t ev;
  tv->has_focus = 1;
  for (;;) {
    int k;
    gtcaca_redraw();
    if (!caca_get_event(gmo.dp, CACA_EVENT_KEY_PRESS, &ev, -1)) continue;
    k = caca_get_event_key_ch(&ev);
    if (k == CACA_KEY_ESCAPE || k == 'q') break;
    if (tv->private_key_cb) tv->private_key_cb(tv, k, NULL);
  }
}

static void tv_destroy(gtcaca_textview_widget_t *tv)
{ gtcaca_textview_clear(tv); CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(tv)); free(tv); }

/* append `data` as printable text, wrapped, each line carrying `prefix`. */
static void tv_block(gtcaca_textview_widget_t *tv, const char *prefix,
                     const uint8_t *d, int len, int width)
{
  char line[600];
  int i = 0, avail = width - (int)strlen(prefix) - 1;
  if (avail < 8) avail = 8;
  if (avail > (int)sizeof line - 1) avail = (int)sizeof line - 1;
  if (len <= 0) return;
  while (i < len) {
    int o = (int)snprintf(line, sizeof line, "%s", prefix), j;
    for (j = 0; j < avail && i < len; j++, i++) {
      uint8_t b = d[i];
      line[o++] = (b >= 32 && b < 127) ? (char)b : '.';
    }
    line[o] = '\0';
    gtcaca_textview_append(tv, line);
  }
}

/* ── Follow TCP / UDP stream ─────────────────────────────────────────────── */
typedef struct { gtcaca_textview_widget_t *tv; uint32_t cip; uint16_t cport; int width; int any; } follow_ctx_t;

static void follow_tcp_cb(void *ud, uint32_t sip, uint16_t sport, uint32_t dip,
                          uint16_t dport, int dir, const uint8_t *data, size_t len,
                          const uint8_t *all, size_t alllen)
{
  follow_ctx_t *f = ud;
  const char *pfx = (sip == f->cip && sport == f->cport) ? "C: " : "S: ";
  (void)dip; (void)dport; (void)dir; (void)all; (void)alllen;
  tv_block(f->tv, pfx, data, (int)len, f->width);
  f->any = 1;
}

static int same_flow(const caracal_l4_t *a, const caracal_l4_t *b)
{
  return (a->sip == b->sip && a->dip == b->dip && a->sport == b->sport && a->dport == b->dport) ||
         (a->sip == b->dip && a->dip == b->sip && a->sport == b->dport && a->dport == b->sport);
}

static void act_follow_tcp(void *u)
{
  long sel = app.table ? gtcaca_table_selected_row(app.table) : -1;
  long pidx = view_pkt_index(sel), i;
  caracal_l4_t l4;
  gtcaca_window_widget_t *win;
  gtcaca_textview_widget_t *tv;
  pcapng_tcp_reasm_t *ctx;
  follow_ctx_t fc;
  int w, h;
  (void)u;

  if (pidx < 0 || !caracal_locate_l4(&app.cap.pkts[pidx], &l4) || l4.proto != 6) {
    gtcaca_dialog_message("Follow TCP Stream", "Select a TCP packet first."); return;
  }
  win = modal_window("Follow TCP Stream", &w, &h);
  tv  = gtcaca_textview_new(GTCACA_WIDGET(win), 1, 1, w - 2, h - 2);
  ctx = pcapng_tcp_reasm_new();
  fc.tv = tv; fc.cip = l4.sip; fc.cport = l4.sport; fc.width = w - 2; fc.any = 0;

  for (i = 0; i < app.cap.count; i++) {
    caracal_l4_t a;
    cpkt_t *p = &app.cap.pkts[i];
    if (!caracal_locate_l4(p, &a) || a.proto != 6 || !same_flow(&a, &l4)) continue;
    pcapng_tcp_reasm_add(ctx, a.sip, a.dip, a.sport, a.dport, a.seq, a.flags,
                         a.paylen > 0 ? p->data + a.payoff : NULL,
                         (size_t)(a.paylen > 0 ? a.paylen : 0), follow_tcp_cb, &fc);
  }
  pcapng_tcp_reasm_free(ctx);
  if (!fc.any) gtcaca_textview_append(tv, "(no stream payload)");
  modal_scroll_loop(tv);
  tv_destroy(tv);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(win)); free(win);
  modal_close_menu();
}

static void act_follow_udp(void *u)
{
  long sel = app.table ? gtcaca_table_selected_row(app.table) : -1;
  long pidx = view_pkt_index(sel), i;
  caracal_l4_t l4;
  gtcaca_window_widget_t *win;
  gtcaca_textview_widget_t *tv;
  int w, h, any = 0;
  (void)u;

  if (pidx < 0 || !caracal_locate_l4(&app.cap.pkts[pidx], &l4) || l4.proto != 17) {
    gtcaca_dialog_message("Follow UDP Stream", "Select a UDP packet first."); return;
  }
  win = modal_window("Follow UDP Stream", &w, &h);
  tv  = gtcaca_textview_new(GTCACA_WIDGET(win), 1, 1, w - 2, h - 2);
  for (i = 0; i < app.cap.count; i++) {
    caracal_l4_t a;
    cpkt_t *p = &app.cap.pkts[i];
    if (!caracal_locate_l4(p, &a) || a.proto != 17 || !same_flow(&a, &l4)) continue;
    if (a.paylen <= 0) continue;
    tv_block(tv, (a.sip == l4.sip && a.sport == l4.sport) ? "C: " : "S: ",
             p->data + a.payoff, a.paylen, w - 2);
    any = 1;
  }
  if (!any) gtcaca_textview_append(tv, "(no datagram payload)");
  modal_scroll_loop(tv);
  tv_destroy(tv);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(win)); free(win);
  modal_close_menu();
}

/* ── IO graph (packets per time interval; all vs filtered) ──────────────── */
static void act_io_graph(void *u)
{
  gtcaca_window_widget_t *win;
  gtcaca_linechart_widget_t *lc;
  int w, h, nb, b;
  double *all, *flt;
  uint64_t t0, t1, span;
  long i;
  char title[160];
  caca_event_t ev;
  (void)u;

  if (app.cap.count == 0) { gtcaca_dialog_message("IO Graph", "No capture loaded."); return; }
  win = modal_window("IO Graph", &w, &h);
  lc  = gtcaca_linechart_new(GTCACA_WIDGET(win), 1, 1, w - 2, h - 2);
  nb  = w - 12; if (nb < 10) nb = 10; if (nb > 240) nb = 240;
  all = calloc((size_t)nb, sizeof *all);
  flt = calloc((size_t)nb, sizeof *flt);

  t0 = t1 = app.cap.pkts[0].ts_us;
  for (i = 0; i < app.cap.count; i++) {
    uint64_t t = app.cap.pkts[i].ts_us;
    if (t > t1) t1 = t; if (t < t0) t0 = t;
  }
  span = (t1 > t0) ? (t1 - t0) : 1;
  for (i = 0; i < app.cap.count && all && flt; i++) {
    cpkt_t *p = &app.cap.pkts[i];
    b = (int)((double)(p->ts_us - t0) / (double)span * (nb - 1));
    if (b < 0) b = 0; if (b >= nb) b = nb - 1;
    all[b] += 1.0;
    if (app.filter_text[0] && app.filter) {
      cfield_t *r = dissect_packet(p);
      if (filter_eval(app.filter, r)) flt[b] += 1.0;
      cfield_free(r);
    }
  }
  if (all) gtcaca_linechart_add_series(lc, all, nb, CACA_GREEN);
  if (flt && app.filter_text[0]) gtcaca_linechart_add_series(lc, flt, nb, CACA_YELLOW);
  snprintf(title, sizeof title, "IO Graph  green=all (%ld pkts)%s",
           app.cap.count, app.filter_text[0] ? "   yellow=filter match" : "");
  gtcaca_linechart_set_title(lc, title);
  free(all); free(flt);          /* add_series copied the data */

  lc->has_focus = 1;
  for (;;) { gtcaca_redraw(); if (caca_get_event(gmo.dp, CACA_EVENT_KEY_PRESS, &ev, -1)) break; }
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(lc)); gtcaca_linechart_free(lc);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(win)); free(win);
  modal_close_menu();
}

/* ── Protocol Hierarchy statistics (cf. Wireshark) ──────────────────────── */
typedef struct phnode {
  char name[32];
  long pkts, bytes, end_pkts, end_bytes;
  struct phnode *child, *sibling;
} phnode_t;

static phnode_t *g_ph_root;
static long      g_ph_total_pkts;

static phnode_t *ph_child(phnode_t *parent, const char *name)
{
  phnode_t *c, *last = NULL;
  for (c = parent->child; c; c = c->sibling) { if (!strcmp(c->name, name)) return c; last = c; }
  c = calloc(1, sizeof *c);
  if (!c) return NULL;
  snprintf(c->name, sizeof c->name, "%s", name);
  if (last) last->sibling = c; else parent->child = c;
  return c;
}
static void ph_free(phnode_t *n)
{
  phnode_t *c, *nx;
  if (!n) return;
  for (c = n->child; c; c = nx) { nx = c->sibling; ph_free(c); }
  free(n);
}
static const char *ph_disp(const char *a)
{
  if (!strcmp(a, "frame")) return "Frame";
  if (!strcmp(a, "eth"))   return "Ethernet";
  if (!strcmp(a, "ip"))    return "Internet Protocol v4";
  if (!strcmp(a, "ipv6"))  return "Internet Protocol v6";
  if (!strcmp(a, "udp"))   return "User Datagram Protocol";
  if (!strcmp(a, "tcp"))   return "Transmission Control Protocol";
  if (!strcmp(a, "ntp"))   return "Network Time Protocol";
  if (!strcmp(a, "dns"))   return "Domain Name System";
  if (!strcmp(a, "data"))  return "Data";
  return a;
}

/* current entry resolver for the tree model */
static phnode_t *ph_at(phnode_t *node, int i)
{
  phnode_t *c = node ? node->child : (g_ph_root ? g_ph_root->child : NULL);
  for (; c && i > 0; c = c->sibling) i--;
  return c;
}
static long ph_count(phnode_t *node)
{
  phnode_t *c = node ? node->child : (g_ph_root ? g_ph_root->child : NULL);
  long n = 0;
  for (; c; c = c->sibling) n++;
  return n;
}

/* A shared progressbar widget, drawn by the cell renderer at each row's rect
   (kept out of the global draw list — we paint it ourselves per row). */
static gtcaca_progressbar_widget_t *g_ph_bar;

static long phm_cc(gtcaca_tree_model_t *m, void *node) { (void)m; return ph_count(node); }
static void *phm_child(gtcaca_tree_model_t *m, void *node, long i) { (void)m; return ph_at(node, (int)i); }
static int  phm_has(gtcaca_tree_model_t *m, void *node) { phnode_t *n = node; (void)m; return n && n->child != NULL; }
static void phm_label(gtcaca_tree_model_t *m, void *node, char *b, int len)
{ phnode_t *n = node; (void)m; snprintf(b, len, "%s", ph_disp(n->name)); }

/* Cell renderer: name + counts on the left, a real gtcaca progressbar (percent
   of packets) on the right — a widget living inside the tree row. */
static void ph_draw_row(gtcaca_tree_model_t *m, void *node, int x, int y, int width, int selected)
{
  phnode_t *n = node;
  double pp = g_ph_total_pkts ? (double)n->pkts / (double)g_ph_total_pkts : 0.0;
  char left[120];
  int barw = width * 42 / 100, leftw;
  (void)m; (void)selected;
  if (barw < 14) barw = 14;
  if (barw > width - 6) barw = width > 6 ? width - 6 : 0;
  leftw = width - barw - 1; if (leftw < 4) leftw = 4;
  snprintf(left, sizeof left, "%s  %ld pk %ld B", ph_disp(n->name), n->pkts, n->bytes);
  if ((int)strlen(left) > leftw) left[leftw] = '\0';
  caca_put_str(gmo.cv, x, y, left);           /* inherits the row colour set by the tree */
  if (g_ph_bar && barw >= 8) {
    g_ph_bar->x = x + leftw + 1; g_ph_bar->y = y; g_ph_bar->width = barw;
    gtcaca_progressbar_set_value(g_ph_bar, (float)pp);
    gtcaca_progressbar_draw(g_ph_bar);
  }
}
static gtcaca_tree_model_t ph_model = { phm_cc, phm_child, phm_label, phm_has, NULL, ph_draw_row };

/* Protocol Hierarchy: an expandable tree whose rows host a real progressbar
   widget via the tree's cell-renderer delegate. */
static void act_proto_stats(void *u)
{
  gtcaca_window_widget_t *win;
  gtcaca_tree_widget_t *tree;
  int w, h;
  long k;
  caca_event_t ev;
  (void)u;

  if (app.nview == 0) { gtcaca_dialog_message("Protocol Hierarchy", "No packets to summarise."); return; }

  g_ph_root = calloc(1, sizeof *g_ph_root);
  g_ph_total_pkts = app.nview;
  for (k = 0; k < app.nview; k++) {
    cpkt_t *p = &app.cap.pkts[view_pkt_index(k)];
    cfield_t *root = dissect_packet(p);
    phnode_t *cur = g_ph_root, *last = NULL;
    int j, nc;
    if (!root) continue;
    nc = cfield_count(root);
    for (j = 0; j < nc; j++) {
      cfield_t *ch = cfield_child_at(root, j);
      phnode_t *pn;
      if (!ch->abbrev[0] || ch->vtype != CV_NONE) continue;   /* protocol layers only */
      pn = ph_child(cur, ch->abbrev);
      if (!pn) break;
      pn->pkts++;
      pn->bytes += ch->len > 0 ? ch->len : 0;
      cur = pn; last = pn;
    }
    if (last) { last->end_pkts++; last->end_bytes += p->origlen; }
    cfield_free(root);
  }

  win = modal_window("Protocol Hierarchy Statistics", &w, &h);
  /* a standalone progressbar the cell renderer repositions per row */
  g_ph_bar = gtcaca_progressbar_new(NULL, 0, 0, 10);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(g_ph_bar));
  tree = gtcaca_tree_new(GTCACA_WIDGET(win), 1, 1, w - 2, h - 2);
  gtcaca_tree_set_model(tree, &ph_model);
  gtcaca_tree_set_title(tree, "Protocol  (Right/Enter expand, Esc close)");
  tree->has_focus = 1;
  for (;;) {
    int key;
    gtcaca_redraw();
    if (!caca_get_event(gmo.dp, CACA_EVENT_KEY_PRESS, &ev, -1)) continue;
    key = caca_get_event_key_ch(&ev);
    if (key == CACA_KEY_ESCAPE || key == 'q') break;
    gtcaca_tree_key(tree, key, NULL);
  }
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(tree)); gtcaca_tree_free(tree);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(win)); free(win);
  free(g_ph_bar); g_ph_bar = NULL;
  ph_free(g_ph_root); g_ph_root = NULL;
  modal_close_menu();
}

/* ── posa editor (with a help panel) ────────────────────────────────────── */
static const char POSA_TEMPLATE[] =
  "# A custom protocol decoder (.posa).\n"
  "# Bind it to a port afterwards via  Analyze > Decode As  (e.g. 'udp 9999 MyProto').\n"
  "\n"
  "Object<main> MyProto\n"
  "    required uint16 opcode = 0\n"
  "        HELLO = 1\n"
  "        BYE   = 2\n"
  "    required uint32 length = 0\n"
  "    required payload data\n";

static const char *POSA_HELP[] = {
  "posa quick reference", "",
  "Object<parent> NAME", "   start a protocol", "",
  "required <type> name = def", "    ENUM = value   (indented", "    lines add enum labels)", "",
  "types:", "  uint8/16/32/64", "  le_uint16/32/64", "  mac, ip4, cstring",
  "  payload  (rest)", "  bytes<N> (fixed)", "  bytes[lenfield]", "",
  "Object<parent> groups sub-", "protocols dispatched on the", "first field's value.", "",
  "^S  save & load", "Esc close",
};

static void act_posa_new(void *u)
{
  gtcaca_window_widget_t *win;
  gtcaca_editor_widget_t *ed;
  gtcaca_textview_widget_t *help;
  gtcaca_editor_grammar_t *grammar;
  int w, h, edw, i;
  caca_event_t ev;
  (void)u;

  win = modal_window("New .posa decoder", &w, &h);
  edw = w * 62 / 100; if (edw < 20) edw = w - 2;
  ed  = gtcaca_editor_new(GTCACA_WIDGET(win), 1, 1, edw, h - 2);
  gtcaca_editor_set_text(ed, POSA_TEMPLATE);
  /* TextMate-grammar syntax colouring (needs gtcaca built with Oniguruma). */
  {
    char gpath[1024];
    snprintf(gpath, sizeof gpath, "%s/posa.tmLanguage.json", grammars_dir());
    grammar = gtcaca_editor_grammar_load(gpath);
  }
  if (grammar) gtcaca_editor_set_grammar(ed, grammar);
  help = (edw < w - 4)
       ? gtcaca_textview_new(GTCACA_WIDGET(win), edw + 2, 1, w - edw - 3, h - 2) : NULL;
  if (help)
    for (i = 0; i < (int)(sizeof POSA_HELP / sizeof *POSA_HELP); i++)
      gtcaca_textview_append(help, POSA_HELP[i]);

  ed->has_focus = 1;
  for (;;) {
    int k;
    gtcaca_redraw();
    if (!caca_get_event(gmo.dp, CACA_EVENT_KEY_PRESS, &ev, -1)) continue;
    k = caca_get_event_key_ch(&ev);
    if (k == CACA_KEY_ESCAPE) break;
    if (k == CTRL('s')) {
      char fn[512], err[160];
      if (prompt_line("Save .posa as:  ", fn, sizeof fn)) {
        FILE *f = fopen(fn, "w");
        if (f) {
          int len = gtcaca_editor_get_length(ed);
          char *buf = malloc((size_t)len + 1);
          if (buf) { gtcaca_editor_get_text(ed, buf, len + 1); fputs(buf, f); free(buf); }
          fclose(f);
          if (posa_load_file(fn, err, sizeof err) < 0) {
            gtcaca_dialog_message("Save failed", err);
          } else {
            invalidate_summaries(); view_rebuild();
            detail_rebuild(app.table ? gtcaca_table_selected_row(app.table) : 0);
            gtcaca_dialog_message("Saved", "Decoder loaded. Bind it with Analyze > Decode As.");
          }
        } else gtcaca_dialog_message("Save failed", "Could not open file for writing.");
      }
      continue;
    }
    if (ed->private_key_cb) ed->private_key_cb(ed, k, NULL);
  }

  if (help) tv_destroy(help);
  if (grammar) gtcaca_editor_set_grammar(ed, NULL);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(ed)); gtcaca_editor_free(ed);
  if (grammar) gtcaca_editor_grammar_free(grammar);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(win)); free(win);
  modal_close_menu();
}

/* ── Decoders window (list built-in + posa, import, new) ────────────────── */
static const char *BUILTIN_DECODERS[] = {
  "frame","eth","vlan","ip","ipv6","arp","tcp","udp","icmp","icmpv6","igmp","gre",
  "dns","mdns","llmnr","nbns","ntp","dhcp","snmp","radius","syslog",
  "tls","ssh","http","ftp","smtp","pop","imap","telnet","irc","redis","rdp"
};

static void decoders_fill(gtcaca_textview_widget_t *tv)
{
  char line[160];
  int i, n = (int)(sizeof BUILTIN_DECODERS / sizeof *BUILTIN_DECODERS);
  gtcaca_textview_clear(tv);
  gtcaca_textview_append(tv, "Built-in decoders:");
  for (i = 0; i < n; i += 6) {
    int j, o = 2;
    line[0] = ' '; line[1] = ' ';
    for (j = i; j < i + 6 && j < n; j++)
      o += snprintf(line + o, sizeof line - o, "%-13s", BUILTIN_DECODERS[j]);
    line[o] = '\0';
    gtcaca_textview_append(tv, line);
  }
  gtcaca_textview_append(tv, "");
  snprintf(line, sizeof line, "Loaded .posa decoders (%d):", posa_count());
  gtcaca_textview_append(tv, line);
  for (i = 0; i < posa_count(); i++) {
    const posa_proto_t *p = posa_at(i);
    snprintf(line, sizeof line, "  %-24s  (group: %s)", p->name, p->parent);
    gtcaca_textview_append(tv, line);
  }
  gtcaca_textview_append(tv, "");
  gtcaca_textview_append(tv, "[i] import .posa    [n] new decoder    [Esc] close");
}

static void act_decoders(void *u)
{
  gtcaca_window_widget_t *win;
  gtcaca_textview_widget_t *tv;
  int w, h, open_editor = 0;
  caca_event_t ev;
  (void)u;

  win = modal_window("Decoders", &w, &h);
  tv  = gtcaca_textview_new(GTCACA_WIDGET(win), 1, 1, w - 2, h - 2);
  decoders_fill(tv);
  tv->has_focus = 1;

  for (;;) {
    int k;
    gtcaca_redraw();
    if (!caca_get_event(gmo.dp, CACA_EVENT_KEY_PRESS, &ev, -1)) continue;
    k = caca_get_event_key_ch(&ev);
    if (k == CACA_KEY_ESCAPE || k == 'q') break;
    if (k == 'i') {
      char path[1024], err[160];
      if (gtcaca_filechooser_run(".", path, sizeof path, 0)) {
        if (posa_load_file(path, err, sizeof err) < 0) gtcaca_dialog_message("Import failed", err);
        else { invalidate_summaries(); view_rebuild();
               detail_rebuild(app.table ? gtcaca_table_selected_row(app.table) : 0); }
      }
      decoders_fill(tv);
      continue;
    }
    if (k == 'n') { open_editor = 1; break; }
    if (tv->private_key_cb) tv->private_key_cb(tv, k, NULL);
  }
  tv_destroy(tv);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(win)); free(win);
  modal_close_menu();
  if (open_editor) act_posa_new(NULL);
}

/* ───────────────────────── View: show/hide detail panes ───────────────── */
static int g_view_entry = -1, g_item_details, g_item_bytes;

/* Recompute geometry from the show_tree/show_hex flags: the packet table grows
   to fill whatever the detail panes give up. */
static void relayout(void)
{
  int W = caca_get_canvas_width(gmo.cv), H = caca_get_canvas_height(gmo.cv);
  int top = 2, bottom = H - 1;            /* below filter row, above status */
  int shown = (app.show_tree ? 1 : 0) + (app.show_hex && app.hex ? 1 : 0);
  int th, dy, dh;

  th = (shown == 0) ? (bottom - top) : (bottom - top) * 55 / 100;
  if (th < 4) th = 4;
  app.table_y = top; app.table_h = th;
  app.table->x = 0; app.table->y = top; app.table->width = W; app.table->height = th;
  app.table->is_visible = 1;

  dy = top + th; dh = bottom - dy; if (dh < 3) dh = 3;
  app.tree_y = dy; app.tree_h = dh;

  if (app.tree) app.tree->is_visible = 0;
  if (app.hex)  app.hex->is_visible  = 0;

  if (app.show_tree && app.show_hex && app.hex) {
    int tw = W * 60 / 100;
    app.tree_w = tw;
    app.tree->x = 0; app.tree->y = dy; app.tree->width = tw; app.tree->height = dh; app.tree->is_visible = 1;
    app.hex->x = tw; app.hex->y = dy; app.hex->width = W - tw; app.hex->height = dh; app.hex->is_visible = 1;
  } else if (app.show_tree) {
    app.tree_w = W;
    app.tree->x = 0; app.tree->y = dy; app.tree->width = W; app.tree->height = dh; app.tree->is_visible = 1;
  } else if (app.show_hex && app.hex) {
    app.hex->x = 0; app.hex->y = dy; app.hex->width = W; app.hex->height = dh; app.hex->is_visible = 1;
  }

  /* don't leave focus on a hidden pane */
  if (app.focus == FOCUS_TREE && !app.show_tree) app.focus = FOCUS_TABLE;
  if (app.focus == FOCUS_HEX  && !(app.show_hex && app.hex)) app.focus = FOCUS_TABLE;
}

static void update_view_labels(void)
{
  if (g_view_entry < 0 || !app.menu) return;
  snprintf(app.menu->entries[g_view_entry].items[g_item_details].label, GTCACA_MENU_LABEL_MAX,
           "[%c] Packet Details", app.show_tree ? 'x' : ' ');
  snprintf(app.menu->entries[g_view_entry].items[g_item_bytes].label, GTCACA_MENU_LABEL_MAX,
           "[%c] Packet Bytes", (app.show_hex && app.hex) ? 'x' : ' ');
}

static void act_toggle_details(void *u)
{ (void)u; app.show_tree = !app.show_tree; relayout(); update_view_labels(); }

static void act_toggle_bytes(void *u)
{
  (void)u;
  if (!app.hex) { gtcaca_dialog_message("Packet Bytes", "The byte pane needs a wider terminal."); return; }
  app.show_hex = !app.show_hex; relayout(); update_view_labels();
}

static void build_menu(void)
{
  int e;
  app.menu = gtcaca_menu_new();

  e = gtcaca_menu_add_entry(app.menu, "File");
  gtcaca_menu_add_item(app.menu, e, "Open\xe2\x80\xa6",     "F2",  act_open,      NULL);
  gtcaca_menu_add_item(app.menu, e, "Reload",               "",    act_reload,    NULL);
  gtcaca_menu_add_separator(app.menu, e);
  gtcaca_menu_add_item(app.menu, e, "Quit",                 "^Q",  act_quit,      NULL);

  e = gtcaca_menu_add_entry(app.menu, "Edit");
  gtcaca_menu_add_item(app.menu, e, "Find Packet\xe2\x80\xa6", "^F", act_find,      NULL);
  gtcaca_menu_add_item(app.menu, e, "Find Next",            "n",   act_find_next, NULL);
  gtcaca_menu_add_item(app.menu, e, "Find Previous",        "N",   act_find_prev, NULL);

  g_view_entry  = gtcaca_menu_add_entry(app.menu, "View");
  g_item_details = gtcaca_menu_add_item(app.menu, g_view_entry, "[x] Packet Details", "", act_toggle_details, NULL);
  g_item_bytes   = gtcaca_menu_add_item(app.menu, g_view_entry, "[x] Packet Bytes",   "", act_toggle_bytes,   NULL);

  e = gtcaca_menu_add_entry(app.menu, "Analyze");
  gtcaca_menu_add_item(app.menu, e, "Follow TCP Stream",    "",    act_follow_tcp, NULL);
  gtcaca_menu_add_item(app.menu, e, "Follow UDP Stream",    "",    act_follow_udp, NULL);
  gtcaca_menu_add_separator(app.menu, e);
  gtcaca_menu_add_item(app.menu, e, "Decode As\xe2\x80\xa6", "",   act_decode_as, NULL);
  gtcaca_menu_add_item(app.menu, e, "Decoders\xe2\x80\xa6",  "",   act_decoders,  NULL);

  e = gtcaca_menu_add_entry(app.menu, "Statistics");
  gtcaca_menu_add_item(app.menu, e, "Protocol Hierarchy",   "",    act_proto_stats, NULL);
  gtcaca_menu_add_item(app.menu, e, "IO Graph",             "",    act_io_graph,  NULL);

  e = gtcaca_menu_add_entry(app.menu, "Help");
  gtcaca_menu_add_item(app.menu, e, "About",                "",    act_about,     NULL);
}

/* ───────────────────────── focus + redraw sync ────────────────────────── */
static void sync_focus(void)
{
  if (app.fentry) app.fentry->has_focus = (app.focus == FOCUS_FILTER);
  if (app.table)  app.table->has_focus  = (app.focus == FOCUS_TABLE);
  if (app.tree)   app.tree->has_focus   = (app.focus == FOCUS_TREE);
  if (app.hex)    app.hex->has_focus    = (app.focus == FOCUS_HEX);
}

static void redraw(void)
{
  /* Track table selection: rebuild the detail tree when it moves. */
  if (app.table) {
    long sel = gtcaca_table_selected_row(app.table);
    if (sel != app.detail_for) detail_rebuild(sel);
  }
  hex_sync_highlight();
  if (app.matchbar) {
    char lbl[24];
    long total = app.cap.count;
    float frac = total ? (float)app.nview / (float)total : 1.0f;
    snprintf(lbl, sizeof lbl, "%ld/%ld", app.nview, total);
    gtcaca_gauge_set_value(app.matchbar, frac);
    gtcaca_gauge_set_label(app.matchbar, lbl);
  }
  sync_focus();
  refresh_status();
  gtcaca_redraw();
}

/* feed an editing key to the filter entry */
static void filter_entry_key(int key)
{
  if (app.fentry && app.fentry->private_key_cb)
    app.fentry->private_key_cb(app.fentry, key, NULL);
}

/* ───────────────────────── headless dump (tshark-like) ────────────────── */
static void dump_tree(cfield_t *n, int depth)
{
  cfield_t *c;
  for (c = n->children; c; c = c->next) {
    printf("%*s%s\n", depth * 2, "", c->label[0] ? c->label : c->abbrev);
    dump_tree(c, depth + 1);
  }
}

static int dump_mode(const char *path, const char *expr)
{
  capture_t cap;
  char err[256] = "";
  cfilter_t *flt = NULL;
  long i, shown = 0;
  int printed_detail = 0;

  posa_load_dir(protos_dir());
  /* Optional port binding for scripted testing, e.g. CARACAL_BIND="udp 69 TFTP" */
  {
    const char *b = getenv("CARACAL_BIND");
    char tr[16], pr[64]; unsigned pt;
    if (b && sscanf(b, "%15s %u %63s", tr, &pt, pr) == 3) {
      if (!strcmp(tr, "udp")) posa_bind_udp((uint16_t)pt, pr);
      else if (!strcmp(tr, "tcp")) posa_bind_tcp((uint16_t)pt, pr);
    }
  }
  if (capture_load(path, &cap, err, sizeof err) != 0) {
    fprintf(stderr, "caracal: %s\n", err);
    return 1;
  }
  if (expr && *expr) {
    flt = filter_compile(expr, err, sizeof err);
    if (!flt) { fprintf(stderr, "caracal: filter: %s\n", err); capture_free(&cap); return 1; }
  }
  printf("# %s — %ld packets, %d custom protocol(s) loaded\n",
         path, cap.count, posa_count());
  if (expr && *expr) printf("# filter: %s\n", expr);

  for (i = 0; i < cap.count; i++) {
    cpkt_t *p = &cap.pkts[i];
    cfield_t *root = dissect_packet(p);
    if (!flt || filter_eval(flt, root)) {
      double t = (double)((p->ts_us >= cap.first_ts_us) ? p->ts_us - cap.first_ts_us : 0) / 1e6;
      dissect_summarize(p);
      printf("%5ld  %.6f  %-15s %-15s %-8s %5u  %s\n",
             i + 1, t, p->col_src, p->col_dst, p->col_proto, p->origlen, p->col_info);
      shown++;
      if (!printed_detail) {
        printf("       └─ detail:\n");
        dump_tree(root, 4);
        printed_detail = 1;
      }
    }
    cfield_free(root);
  }
  printf("# %ld packet(s) matched\n", shown);
  if (flt) filter_free(flt);
  capture_free(&cap);
  return 0;
}

/* ───────────────────────── lua mode (generalized MQS) ─────────────────── */
static void apply_bind(const char *spec)   /* "udp 69 TFTP" */
{
  char tr[16], pr[64]; unsigned pt;
  if (sscanf(spec, "%15s %u %63s", tr, &pt, pr) != 3) {
    fprintf(stderr, "caracal: bad -X binding '%s' (want '<udp|tcp> <port> <Proto>')\n", spec);
    return;
  }
  if (!strcmp(tr, "udp")) posa_bind_udp((uint16_t)pt, pr);
  else if (!strcmp(tr, "tcp")) posa_bind_tcp((uint16_t)pt, pr);
  else fprintf(stderr, "caracal: -X transport must be udp or tcp\n");
}

static int lua_cli(int argc, char **argv)
{
  const char *script = NULL, *capf = NULL, *filt = NULL;
  const char *binds[32]; int nbinds = 0;
  const char *posas[32]; int nposas = 0;
  capture_t cap;
  cfilter_t *flt = NULL;
  char err[256] = "";
  int i, rc;

  for (i = 1; i < argc; i++) {
    if      ((!strcmp(argv[i], "-s") || !strcmp(argv[i], "--script")) && i + 1 < argc) script = argv[++i];
    else if (!strcmp(argv[i], "-r") && i + 1 < argc) capf = argv[++i];
    else if (!strcmp(argv[i], "-f") && i + 1 < argc) filt = argv[++i];
    else if (!strcmp(argv[i], "-X") && i + 1 < argc) { if (nbinds < 32) binds[nbinds++] = argv[++i]; }
    else if (!strcmp(argv[i], "-p") && i + 1 < argc) { if (nposas < 32) posas[nposas++] = argv[++i]; }
    else if (argv[i][0] != '-' && !capf) capf = argv[i];
  }

  if (!script) { fprintf(stderr, "caracal: -s <script.lua> is required\n"); return 2; }
  if (!capf)   { fprintf(stderr, "caracal: -r <capture> is required\n"); return 2; }

  posa_load_dir(protos_dir());
  for (i = 0; i < nposas; i++) {
    if (posa_load_file(posas[i], err, sizeof err) < 0)
      fprintf(stderr, "caracal: -p %s: %s\n", posas[i], err);
  }
  for (i = 0; i < nbinds; i++) apply_bind(binds[i]);

  if (capture_load(capf, &cap, err, sizeof err) != 0) {
    fprintf(stderr, "caracal: %s\n", err);
    return 1;
  }
  if (filt && *filt) {
    flt = filter_compile(filt, err, sizeof err);
    if (!flt) { fprintf(stderr, "caracal: filter: %s\n", err); capture_free(&cap); return 1; }
  }

  rc = caracal_lua_run(script, &cap, flt, err, sizeof err);
  if (rc != 0) fprintf(stderr, "caracal: lua: %s\n", err);

  if (flt) filter_free(flt);
  capture_free(&cap);
  return rc ? 1 : 0;
}

static int has_arg(int argc, char **argv, const char *a, const char *b)
{
  int i;
  for (i = 1; i < argc; i++)
    if (!strcmp(argv[i], a) || (b && !strcmp(argv[i], b))) return 1;
  return 0;
}

/* ───────────────────────── main ───────────────────────────────────────── */
int main(int argc, char **argv)
{
  gtcaca_application_widget_t *appw;
  gtcaca_window_widget_t *win;
  int W, H;
  int int_w;
  int widths[7];

  app.detail_for = -1;

  /* Headless mode for scripting/testing: caracal --dump <file> [filter] */
  if (argc >= 3 && strcmp(argv[1], "--dump") == 0)
    return dump_mode(argv[2], argc > 3 ? argv[3] : NULL);

  /* Lua scripting mode (generalized MQS): caracal -s script.lua -r cap … */
  if (has_arg(argc, argv, "-s", "--script"))
    return lua_cli(argc, argv);

  if (gtcaca_init(&argc, &argv) < 0) {
    fprintf(stderr, "caracal: cannot initialize display\n");
    return 1;
  }

  /* Load bundled protocol definitions (best effort). */
  posa_load_dir(protos_dir());

  W = caca_get_canvas_width(gmo.cv);
  H = caca_get_canvas_height(gmo.cv);

  appw = gtcaca_application_new("caracal");
  win  = gtcaca_window_new(GTCACA_WIDGET(appw), NULL, 0, 0, W, H);

  build_menu();

  gtcaca_label_new(GTCACA_WIDGET(win), "Filter:", 0, 1);
  if (W >= 60) {
    int gw = 18;                       /* filter-match gauge at the right */
    app.fentry = gtcaca_entry_new(GTCACA_WIDGET(win), 8, 1, W - 9 - gw - 1);
    app.matchbar = gtcaca_gauge_new(GTCACA_WIDGET(win), W - gw, 1, gw);
    gtcaca_gauge_set_colors(app.matchbar, CACA_GREEN, CACA_BLUE);
    gtcaca_gauge_set_value(app.matchbar, 1.0f);
  } else {
    app.fentry = gtcaca_entry_new(GTCACA_WIDGET(win), 8, 1, W - 9);
  }

  app.table_y = 2;
  app.table_h = (H - 4) * 55 / 100;
  if (app.table_h < 4) app.table_h = 4;
  app.tree_y  = app.table_y + app.table_h;
  app.tree_h  = H - 1 - app.tree_y;
  if (app.tree_h < 3) app.tree_h = 3;

  app.table = gtcaca_table_new(GTCACA_WIDGET(win), 0, app.table_y, W, app.table_h);
  gtcaca_table_set_model(app.table, &table_model);
  gtcaca_table_set_title(app.table, "Packets");

  int_w = W - 2;
  widths[0] = 7;  widths[1] = 12; widths[2] = 18; widths[3] = 18;
  widths[4] = 9;  widths[5] = 7;
  widths[6] = int_w - (widths[0]+widths[1]+widths[2]+widths[3]+widths[4]+widths[5]);
  if (widths[6] < 6) widths[6] = 6;
  gtcaca_table_set_column_widths(app.table, widths, 7);

  /* Lower area is split: detail tree on the left, hex byte pane on the right. */
  app.tree_w = W * 60 / 100;
  if (app.tree_w < 20) app.tree_w = W;
  app.tree = gtcaca_tree_new(GTCACA_WIDGET(win), 0, app.tree_y, app.tree_w, app.tree_h);
  gtcaca_tree_set_model(app.tree, &tree_model);
  gtcaca_tree_set_title(app.tree, "Packet details");

  if (app.tree_w < W) {
    app.hex = gtcaca_hexview_new(GTCACA_WIDGET(win), app.tree_w, app.tree_y,
                                 W - app.tree_w, app.tree_h);
    gtcaca_hexview_set_title(app.hex, "Bytes");
  }

  app.bar = gtcaca_statusbar_new("");

  /* both detail panes shown by default; relayout sizes everything */
  app.show_tree = 1;
  app.show_hex  = (app.hex != NULL);
  relayout();
  update_view_labels();

  /* Open a file passed on the command line. */
  if (argc > 1) load_capture(argv[1]);
  else { app.filter = filter_compile("", NULL, 0); }

  app.focus = FOCUS_TABLE;

  /* ── event loop ──────────────────────────────────────────────────────── */
  caca_set_mouse(gmo.dp, 1);
  redraw();
  while (!g_quit) {
    caca_event_t ev;
    int t, key;

    if (!caca_get_event(gmo.dp, CACA_EVENT_ANY, &ev, -1)) continue;
    t = caca_get_event_type(&ev);

    if (t & CACA_EVENT_RESIZE) { redraw(); continue; }

    if (t & CACA_EVENT_MOUSE_PRESS) {
      int b  = caca_get_event_mouse_button(&ev);
      int mx = caca_get_mouse_x(gmo.dp);
      int my = caca_get_mouse_y(gmo.dp);
      if (b == 4 || b == 5) {                       /* wheel → scroll focused */
        int k = (b == 4) ? CACA_KEY_DOWN : CACA_KEY_UP;
        if (app.focus == FOCUS_TREE)              gtcaca_tree_key(app.tree, k, NULL);
        else if (app.focus == FOCUS_HEX && app.hex) gtcaca_hexview_key(app.hex, k, NULL);
        else                                      gtcaca_table_key(app.table, k, NULL);
      } else if (b == 1) {                          /* left click → focus pane */
        if (my == 1)                         app.focus = FOCUS_FILTER;
        else if (my >= app.tree_y && app.hex && mx >= app.tree_w) app.focus = FOCUS_HEX;
        else if (my >= app.tree_y)           app.focus = FOCUS_TREE;
        else if (my >= app.table_y) {
          long row = app.table->top + (my - (app.table_y + 3));
          app.focus = FOCUS_TABLE;
          if (row >= 0 && row < app.nview) app.table->sel = row;
        }
      }
      redraw();
      continue;
    }

    if (!(t & CACA_EVENT_KEY_PRESS)) continue;
    key = caca_get_event_key_ch(&ev);

    /* menu owns input while open */
    if (app.menu->has_focus) {
      if (key == CACA_KEY_ESCAPE) { app.menu->has_focus = 0; app.menu->is_open = 0; }
      else gtcaca_menu_handle_key(app.menu, key);
      redraw();
      continue;
    }

    /* global keys */
    if (key == CACA_KEY_F10) { app.menu->has_focus = 1; app.menu->active_entry = 0; app.menu->is_open = 0; redraw(); continue; }
    if (key == CACA_KEY_F2)  { act_open(NULL); redraw(); continue; }
    if (key == CTRL('q'))    { if (confirm_quit()) break; redraw(); continue; }
    if (key == CTRL('o'))    { act_open(NULL); redraw(); continue; }
    if (key == CTRL('f'))    { act_find(NULL); redraw(); continue; }
    if (key == '\t') {
      app.focus = (app.focus + 1) % FOCUS_COUNT;
      if (app.focus == FOCUS_HEX && !app.hex) app.focus = FOCUS_FILTER;
      redraw();
      continue;
    }

    if (app.focus == FOCUS_FILTER) {
      if (key == CACA_KEY_RETURN || key == 10) {
        apply_filter(gtcaca_entry_get_text(app.fentry));
        app.focus = FOCUS_TABLE;
      } else if (key == CACA_KEY_ESCAPE) {
        app.focus = FOCUS_TABLE;
      } else {
        filter_entry_key(key);
      }
      redraw();
      continue;
    }

    /* '/' focuses the filter from a table/tree pane */
    if (key == '/') { app.focus = FOCUS_FILTER; redraw(); continue; }
    /* n / N step through find matches (when a search is active) */
    if (app.find_active && (key == 'n' || key == 'N')) {
      find_jump(key == 'n' ? +1 : -1); redraw(); continue;
    }
    if (key == 'q' || key == 'Q') { if (confirm_quit()) break; redraw(); continue; }

    if      (app.focus == FOCUS_TABLE) gtcaca_table_key(app.table, key, NULL);
    else if (app.focus == FOCUS_HEX && app.hex) gtcaca_hexview_key(app.hex, key, NULL);
    else                               gtcaca_tree_key(app.tree, key, NULL);
    redraw();
  }

  caca_set_mouse(gmo.dp, 0);
  detail_clear();
  if (app.filter) filter_free(app.filter);
  capture_free(&app.cap);
  free(app.view);
  caca_free_display(gmo.dp);
  return 0;
}
