/*
 * caracal — a terminal packet analyzer (a tiny Wireshark for the TUI).
 *
 *   caracal [capture.pcap|.pcapng]
 *
 * Layout:  [menu bar] / [display-filter entry] / [packet table] /
 *          [packet-detail tree] / [status bar]
 *
 * Built on gtcaca's lazy Table and Tree widgets and libpcapng for reading
 * pcapng. Custom protocols are added at runtime by loading .posa definitions
 * (File ▸ Load .posa) and binding them to ports (Analyze ▸ Decode As…).
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#include <caca.h>

#include <gtcaca/main.h>
#include <gtcaca/application.h>
#include <gtcaca/window.h>
#include <gtcaca/menu.h>
#include <gtcaca/table.h>
#include <gtcaca/tree.h>
#include <gtcaca/entry.h>
#include <gtcaca/label.h>
#include <gtcaca/statusbar.h>
#include <gtcaca/dialog.h>
#include <gtcaca/filechooser.h>
#include <gtcaca/image.h>
#include <gtcaca/textview.h>
#include <gtcaca/editor.h>
#include <gtcaca/linechart.h>

#include <libpcapng/reassembly_tcp.h>   /* pcapng_tcp_reasm_* for Follow TCP Stream */

#include "caracal.h"
#include "about_image.h"   /* embedded caracal photo (generated by tools/img2c.py) */

#ifndef CARACAL_PROTOS_DIR
#define CARACAL_PROTOS_DIR "protos"
#endif

#define CTRL(c) ((c) & 0x1f)

enum { FOCUS_FILTER = 0, FOCUS_TABLE, FOCUS_TREE };

typedef struct {
  capture_t cap;

  long     *view;        /* indices into cap.pkts that pass the filter        */
  long      nview;
  long      view_cap;
  cfilter_t *filter;
  char      filter_text[256];

  cfield_t *detail_root; /* dissection of the currently selected packet       */
  long      detail_for;  /* view row the detail belongs to (-1 = none)        */

  int       focus;

  /* widgets */
  gtcaca_menu_widget_t      *menu;
  gtcaca_entry_widget_t     *fentry;
  gtcaca_table_widget_t     *table;
  gtcaca_tree_widget_t      *tree;
  gtcaca_textview_widget_t  *hex;     /* byte pane for the selected packet */
  gtcaca_statusbar_widget_t *bar;

  /* find-packet state */
  uint8_t  find_bytes[256];
  int      find_len;
  char     find_str[256];
  int      find_is_hex;
  int      find_active;

  /* layout (for mouse hit-testing) */
  int table_y, table_h, tree_y, tree_h, tree_w;
} app_t;

static app_t app;

/* ───────────────────────── view (filtered index list) ─────────────────── */
static void view_push(long idx)
{
  if (app.nview == app.view_cap) {
    long nc = app.view_cap ? app.view_cap * 2 : 1024;
    long *nv = realloc(app.view, (size_t)nc * sizeof *nv);
    if (!nv) return;
    app.view = nv;
    app.view_cap = nc;
  }
  app.view[app.nview++] = idx;
}

static long view_pkt_index(long row)   /* table row → cap.pkts index */
{
  if (row < 0 || row >= app.nview) return -1;
  return app.view[row];
}

static void view_rebuild(void)
{
  long i;
  app.nview = 0;
  for (i = 0; i < app.cap.count; i++) {
    cfield_t *root;
    int pass;
    if (app.filter == NULL) { view_push(i); continue; }
    root = dissect_packet(&app.cap.pkts[i]);
    pass = filter_eval(app.filter, root);
    cfield_free(root);
    if (pass) view_push(i);
  }
}

static void invalidate_summaries(void)
{
  long i;
  for (i = 0; i < app.cap.count; i++) app.cap.pkts[i].summarized = 0;
}

/* ───────────────────────── detail tree (re)build ──────────────────────── */
static void detail_clear(void)
{
  if (app.detail_root) { cfield_free(app.detail_root); app.detail_root = NULL; }
  app.detail_for = -1;
}

static gtcaca_tree_model_t tree_model;   /* defined below */

/* Wireshark-style byte pane: "offset  hh hh … hh  |ascii|" lines. */
static void hex_fill(const cpkt_t *p)
{
  char line[160];
  long off;
  int i, n;
  if (!app.hex) return;
  gtcaca_textview_clear(app.hex);
  if (!p) return;
  for (off = 0; off < (long)p->caplen; off += 16) {
    int o = 0;
    o += snprintf(line + o, sizeof line - o, "%04lx  ", off);
    n = (int)(p->caplen - off); if (n > 16) n = 16;
    for (i = 0; i < 16; i++) {
      if (i < n) o += snprintf(line + o, sizeof line - o, "%02x ", p->data[off + i]);
      else       o += snprintf(line + o, sizeof line - o, "   ");
      if (i == 7) o += snprintf(line + o, sizeof line - o, " ");
    }
    o += snprintf(line + o, sizeof line - o, " |");
    for (i = 0; i < n; i++) {
      uint8_t b = p->data[off + i];
      line[o++] = (b >= 32 && b < 127) ? (char)b : '.';
    }
    line[o++] = '|'; line[o] = '\0';
    gtcaca_textview_append(app.hex, line);
  }
}

static void detail_rebuild(long row)
{
  long pidx = view_pkt_index(row);
  detail_clear();
  if (pidx >= 0)
    app.detail_root = dissect_packet(&app.cap.pkts[pidx]);
  app.detail_for = row;
  /* Re-set the model so the tree's expand-state is rebuilt against the new
     node pointers (set_model frees the old open-state). */
  if (app.tree) gtcaca_tree_set_model(app.tree, &tree_model);
  hex_fill(pidx >= 0 ? &app.cap.pkts[pidx] : NULL);
}

/* ───────────────────────── table model ────────────────────────────────── */
static long tm_rows(gtcaca_table_model_t *m) { (void)m; return app.nview; }
static int  tm_cols(gtcaca_table_model_t *m) { (void)m; return 7; }

static void tm_header(gtcaca_table_model_t *m, int col, char *b, int l)
{
  static const char *h[] = { "No.", "Time", "Source", "Destination",
                             "Protocol", "Length", "Info" };
  (void)m;
  snprintf(b, l, "%s", (col >= 0 && col < 7) ? h[col] : "");
}

static void tm_cell(gtcaca_table_model_t *m, long row, int col, char *b, int l)
{
  long pidx = view_pkt_index(row);
  cpkt_t *p;
  (void)m;
  if (pidx < 0) { b[0] = '\0'; return; }
  p = &app.cap.pkts[pidx];
  dissect_summarize(p);
  switch (col) {
  case 0: snprintf(b, l, "%ld", pidx + 1); break;
  case 1: {
    double t = (double)((p->ts_us >= app.cap.first_ts_us)
                          ? p->ts_us - app.cap.first_ts_us : 0) / 1e6;
    snprintf(b, l, "%.6f", t);
    break;
  }
  case 2: snprintf(b, l, "%s", p->col_src); break;
  case 3: snprintf(b, l, "%s", p->col_dst); break;
  case 4: snprintf(b, l, "%s", p->col_proto); break;
  case 5: snprintf(b, l, "%u", p->origlen); break;
  case 6: snprintf(b, l, "%s", p->col_info); break;
  default: b[0] = '\0';
  }
}

static gtcaca_table_model_t table_model = { tm_rows, tm_cols, tm_header, tm_cell, NULL };

/* ───────────────────────── tree model ─────────────────────────────────── */
/* Nodes are cfield_t*. The super-root (NULL) maps to detail_root's children. */
static cfield_t *tree_parent(void *node) { return node ? (cfield_t *)node : app.detail_root; }

static long tn_child_count(gtcaca_tree_model_t *m, void *node)
{ (void)m; return cfield_count(tree_parent(node)); }

static void *tn_child(gtcaca_tree_model_t *m, void *node, long i)
{ (void)m; return cfield_child_at(tree_parent(node), (int)i); }

static void tn_label(gtcaca_tree_model_t *m, void *node, char *b, int l)
{
  cfield_t *f = (cfield_t *)node;
  (void)m;
  if (!f) { b[0] = '\0'; return; }
  if (f->label[0]) snprintf(b, l, "%s", f->label);
  else             snprintf(b, l, "%s", f->abbrev);
}

static int tn_has_children(gtcaca_tree_model_t *m, void *node)
{ (void)m; return cfield_count((cfield_t *)node) > 0; }

static gtcaca_tree_model_t tree_model = {
  tn_child_count, tn_child, tn_label, tn_has_children, NULL
};

/* ───────────────────────── status line ────────────────────────────────── */
static void refresh_status(void)
{
  char s[320];
  const char *focusname = app.focus == FOCUS_FILTER ? "filter"
                        : app.focus == FOCUS_TABLE  ? "table" : "tree";
  if (app.cap.count == 0) {
    snprintf(s, sizeof s, " No capture  |  F2 Open  F10 Menu  Tab switch  ^Q quit");
  } else {
    long sel = app.table ? gtcaca_table_selected_row(app.table) : 0;
    snprintf(s, sizeof s,
      " %s  |  %ld/%ld pkts shown  |  sel %ld  |  [%s]  |  / filter  F2 open  F10 menu  ^Q quit",
      app.cap.path[0] ? app.cap.path : "(none)",
      app.nview, app.cap.count, app.nview ? sel + 1 : 0, focusname);
  }
  gtcaca_statusbar_set_text(app.bar, s);
}

/* ───────────────────────── filter handling ────────────────────────────── */
static void apply_filter(const char *expr)
{
  char err[160] = "";
  cfilter_t *nf = filter_compile(expr, err, sizeof err);
  if (!nf) {
    gtcaca_dialog_message("Filter error", err[0] ? err : "invalid display filter");
    return;
  }
  if (app.filter) filter_free(app.filter);
  app.filter = nf;
  snprintf(app.filter_text, sizeof app.filter_text, "%s", expr ? expr : "");
  view_rebuild();
  if (app.table) gtcaca_table_set_current(app.table, 0, 0);
  detail_rebuild(0);
}

/* ───────────────────────── capture loading ────────────────────────────── */
static void load_capture(const char *path)
{
  capture_t nc;
  char err[256] = "";
  if (capture_load(path, &nc, err, sizeof err) != 0) {
    gtcaca_dialog_message("Open failed", err[0] ? err : "could not read file");
    return;
  }
  capture_free(&app.cap);
  app.cap = nc;
  view_rebuild();
  if (app.table) {
    gtcaca_table_set_title(app.table, app.cap.path);
    gtcaca_table_set_current(app.table, 0, 0);
  }
  detail_rebuild(0);
}

/* ───────────────────────── one-line modal prompt ──────────────────────── */
static int prompt_line(const char *label, char *out, int outlen)
{
  int W = caca_get_canvas_width(gmo.cv), H = caca_get_canvas_height(gmo.cv);
  int len = 0;
  caca_event_t ev;
  out[0] = '\0';
  for (;;) {
    int x;
    caca_set_color_ansi(gmo.cv, CACA_BLACK, CACA_WHITE);
    for (x = 0; x < W; x++) caca_put_char(gmo.cv, x, H - 1, ' ');
    caca_printf(gmo.cv, 0, H - 1, "%s%s", label, out);
    caca_refresh_display(gmo.dp);
    if (!caca_get_event(gmo.dp, CACA_EVENT_KEY_PRESS, &ev, -1)) continue;
    {
      int k = caca_get_event_key_ch(&ev);
      if (k == CACA_KEY_RETURN || k == 10) return len > 0;
      if (k == CACA_KEY_ESCAPE) return 0;
      if ((k == CACA_KEY_BACKSPACE || k == CACA_KEY_DELETE) && len > 0) out[--len] = '\0';
      else if (k >= 32 && k < 127 && len < outlen - 1) { out[len++] = (char)k; out[len] = '\0'; }
    }
  }
}

/* ───────────────────────── find packet (string / hex) ─────────────────── */
static const uint8_t *mem_find(const uint8_t *hay, int hlen, const uint8_t *need, int nlen)
{
  int i;
  if (nlen <= 0 || nlen > hlen) return NULL;
  for (i = 0; i <= hlen - nlen; i++)
    if (memcmp(hay + i, need, (size_t)nlen) == 0) return hay + i;
  return NULL;
}

static int hexparse(const char *s, uint8_t *out, int max)
{
  int n = 0;
  while (*s) {
    int hi, lo;
    while (*s == ' ' || *s == ':' || *s == ',') s++;
    if (!*s) break;
    if (!isxdigit((unsigned char)s[0]) || !isxdigit((unsigned char)s[1])) return -1;
    if (n >= max) return -1;
    hi = isdigit((unsigned char)s[0]) ? s[0] - '0' : (tolower(s[0]) - 'a' + 10);
    lo = isdigit((unsigned char)s[1]) ? s[1] - '0' : (tolower(s[1]) - 'a' + 10);
    out[n++] = (uint8_t)((hi << 4) | lo);
    s += 2;
  }
  return n;
}

static int ci_contains(const char *hay, const char *needle)
{
  size_t nl = strlen(needle), i;
  if (!nl) return 1;
  for (i = 0; hay[i]; i++) {
    size_t j = 0;
    while (needle[j] && hay[i + j] &&
           tolower((unsigned char)hay[i + j]) == tolower((unsigned char)needle[j])) j++;
    if (!needle[j]) return 1;
  }
  return 0;
}

/* does packet at cap index match the active find term? */
static int pkt_find_match(long pidx)
{
  cpkt_t *p = &app.cap.pkts[pidx];
  if (app.find_len > 0 &&
      mem_find(p->data, (int)p->caplen, app.find_bytes, app.find_len)) return 1;
  if (!app.find_is_hex && app.find_str[0]) {        /* text also matches columns */
    dissect_summarize(p);
    if (ci_contains(p->col_info, app.find_str) || ci_contains(p->col_src, app.find_str) ||
        ci_contains(p->col_dst, app.find_str)  || ci_contains(p->col_proto, app.find_str))
      return 1;
  }
  return 0;
}

/* jump to the next/prev matching row (dir = +1 / -1), wrapping. */
static int find_jump(int dir)
{
  long i, cur;
  if (!app.find_active || app.nview == 0) return 0;
  cur = app.table ? gtcaca_table_selected_row(app.table) : 0;
  for (i = 1; i <= app.nview; i++) {
    long row = (cur + dir * i) % app.nview;
    if (row < 0) row += app.nview;
    if (pkt_find_match(view_pkt_index(row))) {
      gtcaca_table_set_current(app.table, row, 0);
      detail_rebuild(row);
      return 1;
    }
  }
  return 0;
}

static void act_find(void *u)
{
  char in[256];
  (void)u;
  if (!prompt_line("Find (text, or 'hex:DE AD BE EF'):  ", in, sizeof in)) return;
  if (strncmp(in, "hex:", 4) == 0) {
    int n = hexparse(in + 4, app.find_bytes, (int)sizeof app.find_bytes);
    if (n <= 0) { gtcaca_dialog_message("Find", "Invalid hex bytes."); return; }
    app.find_len = n; app.find_is_hex = 1; app.find_str[0] = '\0';
  } else {
    int n = (int)strlen(in);
    if (n > (int)sizeof app.find_bytes) n = (int)sizeof app.find_bytes;
    memcpy(app.find_bytes, in, (size_t)n);
    app.find_len = n; app.find_is_hex = 0;
    snprintf(app.find_str, sizeof app.find_str, "%s", in);
  }
  app.find_active = 1;
  if (!find_jump(+1)) gtcaca_dialog_message("Find", "No match.");
}

static void act_find_next(void *u) { (void)u; if (app.find_active) find_jump(+1); }
static void act_find_prev(void *u) { (void)u; if (app.find_active) find_jump(-1); }

/* ───────────────────────── menu actions ───────────────────────────────── */
static void act_open(void *u)
{
  char path[1024];
  (void)u;
  if (gtcaca_filechooser_run(app.cap.path[0] ? "." : ".", path, sizeof path, 0))
    load_capture(path);
}

static void act_reload(void *u)
{
  char path[1024];
  (void)u;
  if (!app.cap.path[0]) return;
  snprintf(path, sizeof path, "%s", app.cap.path);
  load_capture(path);
}

static void act_quit(void *u) { (void)u; gtcaca_main_quit(); }

static void act_load_posa(void *u)
{
  char path[1024], err[160] = "", msg[256];
  int rc;
  (void)u;
  if (!gtcaca_filechooser_run(".", path, sizeof path, 0)) return;
  rc = posa_load_file(path, err, sizeof err);
  if (rc < 0) {
    gtcaca_dialog_message("Load .posa failed", err[0] ? err : "parse error");
    return;
  }
  invalidate_summaries();
  view_rebuild();
  detail_rebuild(app.table ? gtcaca_table_selected_row(app.table) : 0);
  snprintf(msg, sizeof msg, "Loaded %d protocol(s). %d total available.",
           rc, posa_count());
  gtcaca_dialog_message("Protocols loaded", msg);
}

static void act_decode_as(void *u)
{
  char line[128], proto[64];
  char transport[16];
  unsigned port;
  (void)u;
  if (posa_count() == 0) {
    gtcaca_dialog_message("Decode As", "No custom protocols loaded.\nUse File \xe2\x96\xb8 Load .posa first.");
    return;
  }
  if (!prompt_line("Decode As (e.g. 'udp 69 TFTP'):  ", line, sizeof line)) return;
  if (sscanf(line, "%15s %u %63s", transport, &port, proto) != 3) {
    gtcaca_dialog_message("Decode As", "Expected: <udp|tcp> <port> <ProtocolName>");
    return;
  }
  if (!posa_find(proto)) {
    /* allow group names too; only warn if neither a proto nor a group */
    int i, isgroup = 0;
    for (i = 0; i < posa_count(); i++)
      if (strcmp(posa_at(i)->parent, proto) == 0) { isgroup = 1; break; }
    if (!isgroup) {
      gtcaca_dialog_message("Decode As", "Unknown protocol name.");
      return;
    }
  }
  if (!strcmp(transport, "udp"))      posa_bind_udp((uint16_t)port, proto);
  else if (!strcmp(transport, "tcp")) posa_bind_tcp((uint16_t)port, proto);
  else { gtcaca_dialog_message("Decode As", "Transport must be 'udp' or 'tcp'."); return; }

  invalidate_summaries();
  view_rebuild();
  detail_rebuild(app.table ? gtcaca_table_selected_row(app.table) : 0);
}

/* About box: render the embedded caracal photo with libcaca (via gtcaca's image
   widget, which dithers an RGBA buffer onto the canvas) plus a short caption.
   The image bytes are compiled in (about_image.h) — nothing is read from disk. */
static void act_about(void *u)
{
  int W = caca_get_canvas_width(gmo.cv), H = caca_get_canvas_height(gmo.cv);
  int w, h, imgh, cols, ix;
  gtcaca_window_widget_t *win;
  gtcaca_image_widget_t *img;
  gtcaca_label_widget_t *l1, *l2, *l3;
  caca_event_t ev;
  (void)u;

  /* Use most of the screen so the dithered photo has enough cells to read. */
  w = W - 8; if (w > 72) w = 72; if (w > W - 2) w = W - 2; if (w < 24) w = 24;
  h = H - 4;               if (h > H - 2) h = H - 2; if (h < 12) h = 12;

  win  = gtcaca_window_new_centered(NULL, "About caracal", w, h);
  imgh = h - 6;            /* rows for the photo; rest for the caption */

  /* Keep the photo's aspect: terminal cells are ~2:1 tall, so the number of
     columns for a given row count is rows * (imgW/imgH) * 2. Centre it. */
  cols = (int)((double)imgh * (double)ABOUT_IMG_W / (double)ABOUT_IMG_H * 2.0 + 0.5);
  if (cols > w - 2) cols = w - 2;
  if (cols < 1) cols = 1;
  ix = (w - cols) / 2; if (ix < 1) ix = 1;

  img = gtcaca_image_new(GTCACA_WIDGET(win), ix, 1, cols, imgh);
  /* Point the widget straight at the embedded RGBA buffer rather than loading a
     file; image_draw() builds a caca_dither from it each frame. */
  img->pixels     = (void *)about_img_rgba;
  img->img_width  = ABOUT_IMG_W;
  img->img_height = ABOUT_IMG_H;

  l1 = gtcaca_label_new(GTCACA_WIDGET(win), "caracal \xe2\x80\x94 a TUI packet analyzer", 2, imgh + 2);
  l2 = gtcaca_label_new(GTCACA_WIDGET(win), "gtcaca + libpcapng + LuaJIT", 2, imgh + 3);
  l3 = gtcaca_label_new(GTCACA_WIDGET(win), "Press any key to close", 2, imgh + 4);

  for (;;) {
    gtcaca_redraw();
    if (!caca_get_event(gmo.dp, CACA_EVENT_KEY_PRESS, &ev, -1)) continue;
    break;
  }

  /* Take the widgets back out of the global draw list, then free. Clear the
     borrowed pixel pointer first so image_free() doesn't free static data. */
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(l3)); free(l3);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(l2)); free(l2);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(l1)); free(l1);
  img->pixels = NULL;
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(img)); gtcaca_image_free(img);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(win)); free(win);

  if (app.menu) { app.menu->is_open = 0; app.menu->has_focus = 0; }
}

/* ───────────────────────── modal windows (follow/graph/decoders/editor) ── */
static gtcaca_window_widget_t *modal_window(const char *title, int *ow, int *oh)
{
  int W = caca_get_canvas_width(gmo.cv), H = caca_get_canvas_height(gmo.cv);
  int w = W - 6, h = H - 4;
  if (w > 130) w = 130;
  if (w < 24) w = 24;
  if (h < 10) h = 10;
  *ow = w; *oh = h;
  return gtcaca_window_new_centered(NULL, (char *)title, w, h);
}

static void modal_close_menu(void)
{ if (app.menu) { app.menu->is_open = 0; app.menu->has_focus = 0; } }

/* scroll a textview until Esc/q */
static void modal_scroll_loop(gtcaca_textview_widget_t *tv)
{
  caca_event_t ev;
  tv->has_focus = 1;
  for (;;) {
    int k;
    gtcaca_redraw();
    if (!caca_get_event(gmo.dp, CACA_EVENT_KEY_PRESS, &ev, -1)) continue;
    k = caca_get_event_key_ch(&ev);
    if (k == CACA_KEY_ESCAPE || k == 'q') break;
    if (tv->private_key_cb) tv->private_key_cb(tv, k, NULL);
  }
}

static void tv_destroy(gtcaca_textview_widget_t *tv)
{ gtcaca_textview_clear(tv); CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(tv)); free(tv); }

/* append `data` as printable text, wrapped, each line carrying `prefix`. */
static void tv_block(gtcaca_textview_widget_t *tv, const char *prefix,
                     const uint8_t *d, int len, int width)
{
  char line[600];
  int i = 0, avail = width - (int)strlen(prefix) - 1;
  if (avail < 8) avail = 8;
  if (avail > (int)sizeof line - 1) avail = (int)sizeof line - 1;
  if (len <= 0) return;
  while (i < len) {
    int o = (int)snprintf(line, sizeof line, "%s", prefix), j;
    for (j = 0; j < avail && i < len; j++, i++) {
      uint8_t b = d[i];
      line[o++] = (b >= 32 && b < 127) ? (char)b : '.';
    }
    line[o] = '\0';
    gtcaca_textview_append(tv, line);
  }
}

/* ── Follow TCP / UDP stream ─────────────────────────────────────────────── */
typedef struct { gtcaca_textview_widget_t *tv; uint32_t cip; uint16_t cport; int width; int any; } follow_ctx_t;

static void follow_tcp_cb(void *ud, uint32_t sip, uint16_t sport, uint32_t dip,
                          uint16_t dport, int dir, const uint8_t *data, size_t len,
                          const uint8_t *all, size_t alllen)
{
  follow_ctx_t *f = ud;
  const char *pfx = (sip == f->cip && sport == f->cport) ? "C: " : "S: ";
  (void)dip; (void)dport; (void)dir; (void)all; (void)alllen;
  tv_block(f->tv, pfx, data, (int)len, f->width);
  f->any = 1;
}

static int same_flow(const caracal_l4_t *a, const caracal_l4_t *b)
{
  return (a->sip == b->sip && a->dip == b->dip && a->sport == b->sport && a->dport == b->dport) ||
         (a->sip == b->dip && a->dip == b->sip && a->sport == b->dport && a->dport == b->sport);
}

static void act_follow_tcp(void *u)
{
  long sel = app.table ? gtcaca_table_selected_row(app.table) : -1;
  long pidx = view_pkt_index(sel), i;
  caracal_l4_t l4;
  gtcaca_window_widget_t *win;
  gtcaca_textview_widget_t *tv;
  pcapng_tcp_reasm_t *ctx;
  follow_ctx_t fc;
  int w, h;
  (void)u;

  if (pidx < 0 || !caracal_locate_l4(&app.cap.pkts[pidx], &l4) || l4.proto != 6) {
    gtcaca_dialog_message("Follow TCP Stream", "Select a TCP packet first."); return;
  }
  win = modal_window("Follow TCP Stream", &w, &h);
  tv  = gtcaca_textview_new(GTCACA_WIDGET(win), 1, 1, w - 2, h - 2);
  ctx = pcapng_tcp_reasm_new();
  fc.tv = tv; fc.cip = l4.sip; fc.cport = l4.sport; fc.width = w - 2; fc.any = 0;

  for (i = 0; i < app.cap.count; i++) {
    caracal_l4_t a;
    cpkt_t *p = &app.cap.pkts[i];
    if (!caracal_locate_l4(p, &a) || a.proto != 6 || !same_flow(&a, &l4)) continue;
    pcapng_tcp_reasm_add(ctx, a.sip, a.dip, a.sport, a.dport, a.seq, a.flags,
                         a.paylen > 0 ? p->data + a.payoff : NULL,
                         (size_t)(a.paylen > 0 ? a.paylen : 0), follow_tcp_cb, &fc);
  }
  pcapng_tcp_reasm_free(ctx);
  if (!fc.any) gtcaca_textview_append(tv, "(no stream payload)");
  modal_scroll_loop(tv);
  tv_destroy(tv);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(win)); free(win);
  modal_close_menu();
}

static void act_follow_udp(void *u)
{
  long sel = app.table ? gtcaca_table_selected_row(app.table) : -1;
  long pidx = view_pkt_index(sel), i;
  caracal_l4_t l4;
  gtcaca_window_widget_t *win;
  gtcaca_textview_widget_t *tv;
  int w, h, any = 0;
  (void)u;

  if (pidx < 0 || !caracal_locate_l4(&app.cap.pkts[pidx], &l4) || l4.proto != 17) {
    gtcaca_dialog_message("Follow UDP Stream", "Select a UDP packet first."); return;
  }
  win = modal_window("Follow UDP Stream", &w, &h);
  tv  = gtcaca_textview_new(GTCACA_WIDGET(win), 1, 1, w - 2, h - 2);
  for (i = 0; i < app.cap.count; i++) {
    caracal_l4_t a;
    cpkt_t *p = &app.cap.pkts[i];
    if (!caracal_locate_l4(p, &a) || a.proto != 17 || !same_flow(&a, &l4)) continue;
    if (a.paylen <= 0) continue;
    tv_block(tv, (a.sip == l4.sip && a.sport == l4.sport) ? "C: " : "S: ",
             p->data + a.payoff, a.paylen, w - 2);
    any = 1;
  }
  if (!any) gtcaca_textview_append(tv, "(no datagram payload)");
  modal_scroll_loop(tv);
  tv_destroy(tv);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(win)); free(win);
  modal_close_menu();
}

/* ── IO graph (packets per time interval; all vs filtered) ──────────────── */
static void act_io_graph(void *u)
{
  gtcaca_window_widget_t *win;
  gtcaca_linechart_widget_t *lc;
  int w, h, nb, b;
  double *all, *flt;
  uint64_t t0, t1, span;
  long i;
  char title[160];
  caca_event_t ev;
  (void)u;

  if (app.cap.count == 0) { gtcaca_dialog_message("IO Graph", "No capture loaded."); return; }
  win = modal_window("IO Graph", &w, &h);
  lc  = gtcaca_linechart_new(GTCACA_WIDGET(win), 1, 1, w - 2, h - 2);
  nb  = w - 12; if (nb < 10) nb = 10; if (nb > 240) nb = 240;
  all = calloc((size_t)nb, sizeof *all);
  flt = calloc((size_t)nb, sizeof *flt);

  t0 = t1 = app.cap.pkts[0].ts_us;
  for (i = 0; i < app.cap.count; i++) {
    uint64_t t = app.cap.pkts[i].ts_us;
    if (t > t1) t1 = t; if (t < t0) t0 = t;
  }
  span = (t1 > t0) ? (t1 - t0) : 1;
  for (i = 0; i < app.cap.count && all && flt; i++) {
    cpkt_t *p = &app.cap.pkts[i];
    b = (int)((double)(p->ts_us - t0) / (double)span * (nb - 1));
    if (b < 0) b = 0; if (b >= nb) b = nb - 1;
    all[b] += 1.0;
    if (app.filter_text[0] && app.filter) {
      cfield_t *r = dissect_packet(p);
      if (filter_eval(app.filter, r)) flt[b] += 1.0;
      cfield_free(r);
    }
  }
  if (all) gtcaca_linechart_add_series(lc, all, nb, CACA_GREEN);
  if (flt && app.filter_text[0]) gtcaca_linechart_add_series(lc, flt, nb, CACA_YELLOW);
  snprintf(title, sizeof title, "IO Graph  green=all (%ld pkts)%s",
           app.cap.count, app.filter_text[0] ? "   yellow=filter match" : "");
  gtcaca_linechart_set_title(lc, title);
  free(all); free(flt);          /* add_series copied the data */

  lc->has_focus = 1;
  for (;;) { gtcaca_redraw(); if (caca_get_event(gmo.dp, CACA_EVENT_KEY_PRESS, &ev, -1)) break; }
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(lc)); gtcaca_linechart_free(lc);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(win)); free(win);
  modal_close_menu();
}

/* ── posa editor (with a help panel) ────────────────────────────────────── */
static const char POSA_TEMPLATE[] =
  "# A custom protocol decoder (.posa).\n"
  "# Bind it to a port afterwards via  Analyze > Decode As  (e.g. 'udp 9999 MyProto').\n"
  "\n"
  "Object<main> MyProto\n"
  "    required uint16 opcode = 0\n"
  "        HELLO = 1\n"
  "        BYE   = 2\n"
  "    required uint32 length = 0\n"
  "    required payload data\n";

static const char *POSA_HELP[] = {
  "posa quick reference", "",
  "Object<parent> NAME", "   start a protocol", "",
  "required <type> name = def", "    ENUM = value   (indented", "    lines add enum labels)", "",
  "types:", "  uint8/16/32/64", "  le_uint16/32/64", "  mac, ip4, cstring",
  "  payload  (rest)", "  bytes<N> (fixed)", "  bytes[lenfield]", "",
  "Object<parent> groups sub-", "protocols dispatched on the", "first field's value.", "",
  "^S  save & load", "Esc close",
};

static void act_posa_new(void *u)
{
  gtcaca_window_widget_t *win;
  gtcaca_editor_widget_t *ed;
  gtcaca_textview_widget_t *help;
  int w, h, edw, i;
  caca_event_t ev;
  (void)u;

  win = modal_window("New .posa decoder", &w, &h);
  edw = w * 62 / 100; if (edw < 20) edw = w - 2;
  ed  = gtcaca_editor_new(GTCACA_WIDGET(win), 1, 1, edw, h - 2);
  gtcaca_editor_set_text(ed, POSA_TEMPLATE);
  help = (edw < w - 4)
       ? gtcaca_textview_new(GTCACA_WIDGET(win), edw + 2, 1, w - edw - 3, h - 2) : NULL;
  if (help)
    for (i = 0; i < (int)(sizeof POSA_HELP / sizeof *POSA_HELP); i++)
      gtcaca_textview_append(help, POSA_HELP[i]);

  ed->has_focus = 1;
  for (;;) {
    int k;
    gtcaca_redraw();
    if (!caca_get_event(gmo.dp, CACA_EVENT_KEY_PRESS, &ev, -1)) continue;
    k = caca_get_event_key_ch(&ev);
    if (k == CACA_KEY_ESCAPE) break;
    if (k == CTRL('s')) {
      char fn[512], err[160];
      if (prompt_line("Save .posa as:  ", fn, sizeof fn)) {
        FILE *f = fopen(fn, "w");
        if (f) {
          int len = gtcaca_editor_get_length(ed);
          char *buf = malloc((size_t)len + 1);
          if (buf) { gtcaca_editor_get_text(ed, buf, len + 1); fputs(buf, f); free(buf); }
          fclose(f);
          if (posa_load_file(fn, err, sizeof err) < 0) {
            gtcaca_dialog_message("Save failed", err);
          } else {
            invalidate_summaries(); view_rebuild();
            detail_rebuild(app.table ? gtcaca_table_selected_row(app.table) : 0);
            gtcaca_dialog_message("Saved", "Decoder loaded. Bind it with Analyze > Decode As.");
          }
        } else gtcaca_dialog_message("Save failed", "Could not open file for writing.");
      }
      continue;
    }
    if (ed->private_key_cb) ed->private_key_cb(ed, k, NULL);
  }

  if (help) tv_destroy(help);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(ed)); gtcaca_editor_free(ed);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(win)); free(win);
  modal_close_menu();
}

/* ── Decoders window (list built-in + posa, import, new) ────────────────── */
static const char *BUILTIN_DECODERS[] = {
  "frame","eth","vlan","ip","ipv6","arp","tcp","udp","icmp","icmpv6","igmp","gre",
  "dns","mdns","llmnr","nbns","ntp","dhcp","snmp","radius","syslog",
  "tls","ssh","http","ftp","smtp","pop","imap","telnet","irc","redis","rdp"
};

static void decoders_fill(gtcaca_textview_widget_t *tv)
{
  char line[160];
  int i, n = (int)(sizeof BUILTIN_DECODERS / sizeof *BUILTIN_DECODERS);
  gtcaca_textview_clear(tv);
  gtcaca_textview_append(tv, "Built-in decoders:");
  for (i = 0; i < n; i += 6) {
    int j, o = 2;
    line[0] = ' '; line[1] = ' ';
    for (j = i; j < i + 6 && j < n; j++)
      o += snprintf(line + o, sizeof line - o, "%-13s", BUILTIN_DECODERS[j]);
    line[o] = '\0';
    gtcaca_textview_append(tv, line);
  }
  gtcaca_textview_append(tv, "");
  snprintf(line, sizeof line, "Loaded .posa decoders (%d):", posa_count());
  gtcaca_textview_append(tv, line);
  for (i = 0; i < posa_count(); i++) {
    const posa_proto_t *p = posa_at(i);
    snprintf(line, sizeof line, "  %-24s  (group: %s)", p->name, p->parent);
    gtcaca_textview_append(tv, line);
  }
  gtcaca_textview_append(tv, "");
  gtcaca_textview_append(tv, "[i] import .posa    [n] new decoder    [Esc] close");
}

static void act_decoders(void *u)
{
  gtcaca_window_widget_t *win;
  gtcaca_textview_widget_t *tv;
  int w, h, open_editor = 0;
  caca_event_t ev;
  (void)u;

  win = modal_window("Decoders", &w, &h);
  tv  = gtcaca_textview_new(GTCACA_WIDGET(win), 1, 1, w - 2, h - 2);
  decoders_fill(tv);
  tv->has_focus = 1;

  for (;;) {
    int k;
    gtcaca_redraw();
    if (!caca_get_event(gmo.dp, CACA_EVENT_KEY_PRESS, &ev, -1)) continue;
    k = caca_get_event_key_ch(&ev);
    if (k == CACA_KEY_ESCAPE || k == 'q') break;
    if (k == 'i') {
      char path[1024], err[160];
      if (gtcaca_filechooser_run(".", path, sizeof path, 0)) {
        if (posa_load_file(path, err, sizeof err) < 0) gtcaca_dialog_message("Import failed", err);
        else { invalidate_summaries(); view_rebuild();
               detail_rebuild(app.table ? gtcaca_table_selected_row(app.table) : 0); }
      }
      decoders_fill(tv);
      continue;
    }
    if (k == 'n') { open_editor = 1; break; }
    if (tv->private_key_cb) tv->private_key_cb(tv, k, NULL);
  }
  tv_destroy(tv);
  CDL_DELETE(gmo.widgets_list, GTCACA_WIDGET(win)); free(win);
  modal_close_menu();
  if (open_editor) act_posa_new(NULL);
}

static void build_menu(void)
{
  int e;
  app.menu = gtcaca_menu_new();

  e = gtcaca_menu_add_entry(app.menu, "File");
  gtcaca_menu_add_item(app.menu, e, "Open\xe2\x80\xa6",     "F2",  act_open,      NULL);
  gtcaca_menu_add_item(app.menu, e, "Reload",               "",    act_reload,    NULL);
  gtcaca_menu_add_separator(app.menu, e);
  gtcaca_menu_add_item(app.menu, e, "Load .posa\xe2\x80\xa6", "",  act_load_posa, NULL);
  gtcaca_menu_add_separator(app.menu, e);
  gtcaca_menu_add_item(app.menu, e, "Quit",                 "^Q",  act_quit,      NULL);

  e = gtcaca_menu_add_entry(app.menu, "Edit");
  gtcaca_menu_add_item(app.menu, e, "Find Packet\xe2\x80\xa6", "^F", act_find,      NULL);
  gtcaca_menu_add_item(app.menu, e, "Find Next",            "n",   act_find_next, NULL);
  gtcaca_menu_add_item(app.menu, e, "Find Previous",        "N",   act_find_prev, NULL);

  e = gtcaca_menu_add_entry(app.menu, "Analyze");
  gtcaca_menu_add_item(app.menu, e, "Follow TCP Stream",    "",    act_follow_tcp, NULL);
  gtcaca_menu_add_item(app.menu, e, "Follow UDP Stream",    "",    act_follow_udp, NULL);
  gtcaca_menu_add_separator(app.menu, e);
  gtcaca_menu_add_item(app.menu, e, "Decode As\xe2\x80\xa6", "",   act_decode_as, NULL);
  gtcaca_menu_add_item(app.menu, e, "Decoders\xe2\x80\xa6",  "",   act_decoders,  NULL);

  e = gtcaca_menu_add_entry(app.menu, "Statistics");
  gtcaca_menu_add_item(app.menu, e, "IO Graph",             "",    act_io_graph,  NULL);

  e = gtcaca_menu_add_entry(app.menu, "Help");
  gtcaca_menu_add_item(app.menu, e, "About",                "",    act_about,     NULL);
}

/* ───────────────────────── focus + redraw sync ────────────────────────── */
static void sync_focus(void)
{
  if (app.fentry) app.fentry->has_focus = (app.focus == FOCUS_FILTER);
  if (app.table)  app.table->has_focus  = (app.focus == FOCUS_TABLE);
  if (app.tree)   app.tree->has_focus   = (app.focus == FOCUS_TREE);
}

static void redraw(void)
{
  /* Track table selection: rebuild the detail tree when it moves. */
  if (app.table) {
    long sel = gtcaca_table_selected_row(app.table);
    if (sel != app.detail_for) detail_rebuild(sel);
  }
  sync_focus();
  refresh_status();
  gtcaca_redraw();
}

/* feed an editing key to the filter entry */
static void filter_entry_key(int key)
{
  if (app.fentry && app.fentry->private_key_cb)
    app.fentry->private_key_cb(app.fentry, key, NULL);
}

/* ───────────────────────── headless dump (tshark-like) ────────────────── */
static void dump_tree(cfield_t *n, int depth)
{
  cfield_t *c;
  for (c = n->children; c; c = c->next) {
    printf("%*s%s\n", depth * 2, "", c->label[0] ? c->label : c->abbrev);
    dump_tree(c, depth + 1);
  }
}

static int dump_mode(const char *path, const char *expr)
{
  capture_t cap;
  char err[256] = "";
  cfilter_t *flt = NULL;
  long i, shown = 0;
  int printed_detail = 0;

  posa_load_dir(CARACAL_PROTOS_DIR);
  /* Optional port binding for scripted testing, e.g. CARACAL_BIND="udp 69 TFTP" */
  {
    const char *b = getenv("CARACAL_BIND");
    char tr[16], pr[64]; unsigned pt;
    if (b && sscanf(b, "%15s %u %63s", tr, &pt, pr) == 3) {
      if (!strcmp(tr, "udp")) posa_bind_udp((uint16_t)pt, pr);
      else if (!strcmp(tr, "tcp")) posa_bind_tcp((uint16_t)pt, pr);
    }
  }
  if (capture_load(path, &cap, err, sizeof err) != 0) {
    fprintf(stderr, "caracal: %s\n", err);
    return 1;
  }
  if (expr && *expr) {
    flt = filter_compile(expr, err, sizeof err);
    if (!flt) { fprintf(stderr, "caracal: filter: %s\n", err); capture_free(&cap); return 1; }
  }
  printf("# %s — %ld packets, %d custom protocol(s) loaded\n",
         path, cap.count, posa_count());
  if (expr && *expr) printf("# filter: %s\n", expr);

  for (i = 0; i < cap.count; i++) {
    cpkt_t *p = &cap.pkts[i];
    cfield_t *root = dissect_packet(p);
    if (!flt || filter_eval(flt, root)) {
      double t = (double)((p->ts_us >= cap.first_ts_us) ? p->ts_us - cap.first_ts_us : 0) / 1e6;
      dissect_summarize(p);
      printf("%5ld  %.6f  %-15s %-15s %-8s %5u  %s\n",
             i + 1, t, p->col_src, p->col_dst, p->col_proto, p->origlen, p->col_info);
      shown++;
      if (!printed_detail) {
        printf("       └─ detail:\n");
        dump_tree(root, 4);
        printed_detail = 1;
      }
    }
    cfield_free(root);
  }
  printf("# %ld packet(s) matched\n", shown);
  if (flt) filter_free(flt);
  capture_free(&cap);
  return 0;
}

/* ───────────────────────── lua mode (generalized MQS) ─────────────────── */
static void apply_bind(const char *spec)   /* "udp 69 TFTP" */
{
  char tr[16], pr[64]; unsigned pt;
  if (sscanf(spec, "%15s %u %63s", tr, &pt, pr) != 3) {
    fprintf(stderr, "caracal: bad -X binding '%s' (want '<udp|tcp> <port> <Proto>')\n", spec);
    return;
  }
  if (!strcmp(tr, "udp")) posa_bind_udp((uint16_t)pt, pr);
  else if (!strcmp(tr, "tcp")) posa_bind_tcp((uint16_t)pt, pr);
  else fprintf(stderr, "caracal: -X transport must be udp or tcp\n");
}

static int lua_cli(int argc, char **argv)
{
  const char *script = NULL, *capf = NULL, *filt = NULL;
  const char *binds[32]; int nbinds = 0;
  const char *posas[32]; int nposas = 0;
  capture_t cap;
  cfilter_t *flt = NULL;
  char err[256] = "";
  int i, rc;

  for (i = 1; i < argc; i++) {
    if      ((!strcmp(argv[i], "-s") || !strcmp(argv[i], "--script")) && i + 1 < argc) script = argv[++i];
    else if (!strcmp(argv[i], "-r") && i + 1 < argc) capf = argv[++i];
    else if (!strcmp(argv[i], "-f") && i + 1 < argc) filt = argv[++i];
    else if (!strcmp(argv[i], "-X") && i + 1 < argc) { if (nbinds < 32) binds[nbinds++] = argv[++i]; }
    else if (!strcmp(argv[i], "-p") && i + 1 < argc) { if (nposas < 32) posas[nposas++] = argv[++i]; }
    else if (argv[i][0] != '-' && !capf) capf = argv[i];
  }

  if (!script) { fprintf(stderr, "caracal: -s <script.lua> is required\n"); return 2; }
  if (!capf)   { fprintf(stderr, "caracal: -r <capture> is required\n"); return 2; }

  posa_load_dir(CARACAL_PROTOS_DIR);
  for (i = 0; i < nposas; i++) {
    if (posa_load_file(posas[i], err, sizeof err) < 0)
      fprintf(stderr, "caracal: -p %s: %s\n", posas[i], err);
  }
  for (i = 0; i < nbinds; i++) apply_bind(binds[i]);

  if (capture_load(capf, &cap, err, sizeof err) != 0) {
    fprintf(stderr, "caracal: %s\n", err);
    return 1;
  }
  if (filt && *filt) {
    flt = filter_compile(filt, err, sizeof err);
    if (!flt) { fprintf(stderr, "caracal: filter: %s\n", err); capture_free(&cap); return 1; }
  }

  rc = caracal_lua_run(script, &cap, flt, err, sizeof err);
  if (rc != 0) fprintf(stderr, "caracal: lua: %s\n", err);

  if (flt) filter_free(flt);
  capture_free(&cap);
  return rc ? 1 : 0;
}

static int has_arg(int argc, char **argv, const char *a, const char *b)
{
  int i;
  for (i = 1; i < argc; i++)
    if (!strcmp(argv[i], a) || (b && !strcmp(argv[i], b))) return 1;
  return 0;
}

/* ───────────────────────── main ───────────────────────────────────────── */
int main(int argc, char **argv)
{
  gtcaca_application_widget_t *appw;
  gtcaca_window_widget_t *win;
  int W, H;
  int int_w;
  int widths[7];

  app.detail_for = -1;

  /* Headless mode for scripting/testing: caracal --dump <file> [filter] */
  if (argc >= 3 && strcmp(argv[1], "--dump") == 0)
    return dump_mode(argv[2], argc > 3 ? argv[3] : NULL);

  /* Lua scripting mode (generalized MQS): caracal -s script.lua -r cap … */
  if (has_arg(argc, argv, "-s", "--script"))
    return lua_cli(argc, argv);

  if (gtcaca_init(&argc, &argv) < 0) {
    fprintf(stderr, "caracal: cannot initialize display\n");
    return 1;
  }

  /* Load bundled protocol definitions (best effort). */
  posa_load_dir(CARACAL_PROTOS_DIR);

  W = caca_get_canvas_width(gmo.cv);
  H = caca_get_canvas_height(gmo.cv);

  appw = gtcaca_application_new("caracal");
  win  = gtcaca_window_new(GTCACA_WIDGET(appw), NULL, 0, 0, W, H);

  build_menu();

  gtcaca_label_new(GTCACA_WIDGET(win), "Filter:", 0, 1);
  app.fentry = gtcaca_entry_new(GTCACA_WIDGET(win), 8, 1, W - 9);

  app.table_y = 2;
  app.table_h = (H - 4) * 55 / 100;
  if (app.table_h < 4) app.table_h = 4;
  app.tree_y  = app.table_y + app.table_h;
  app.tree_h  = H - 1 - app.tree_y;
  if (app.tree_h < 3) app.tree_h = 3;

  app.table = gtcaca_table_new(GTCACA_WIDGET(win), 0, app.table_y, W, app.table_h);
  gtcaca_table_set_model(app.table, &table_model);
  gtcaca_table_set_title(app.table, "Packets");

  int_w = W - 2;
  widths[0] = 7;  widths[1] = 12; widths[2] = 18; widths[3] = 18;
  widths[4] = 9;  widths[5] = 7;
  widths[6] = int_w - (widths[0]+widths[1]+widths[2]+widths[3]+widths[4]+widths[5]);
  if (widths[6] < 6) widths[6] = 6;
  gtcaca_table_set_column_widths(app.table, widths, 7);

  /* Lower area is split: detail tree on the left, hex byte pane on the right. */
  app.tree_w = W * 60 / 100;
  if (app.tree_w < 20) app.tree_w = W;
  app.tree = gtcaca_tree_new(GTCACA_WIDGET(win), 0, app.tree_y, app.tree_w, app.tree_h);
  gtcaca_tree_set_model(app.tree, &tree_model);
  gtcaca_tree_set_title(app.tree, "Packet details");

  if (app.tree_w < W) {
    app.hex = gtcaca_textview_new(GTCACA_WIDGET(win), app.tree_w, app.tree_y,
                                  W - app.tree_w, app.tree_h);
  }

  app.bar = gtcaca_statusbar_new("");

  /* Open a file passed on the command line. */
  if (argc > 1) load_capture(argv[1]);
  else { app.filter = filter_compile("", NULL, 0); }

  app.focus = FOCUS_TABLE;

  /* ── event loop ──────────────────────────────────────────────────────── */
  caca_set_mouse(gmo.dp, 1);
  redraw();
  while (1) {
    caca_event_t ev;
    int t, key;

    if (!caca_get_event(gmo.dp, CACA_EVENT_ANY, &ev, -1)) continue;
    t = caca_get_event_type(&ev);

    if (t & CACA_EVENT_RESIZE) { redraw(); continue; }

    if (t & CACA_EVENT_MOUSE_PRESS) {
      int b  = caca_get_event_mouse_button(&ev);
      int my = caca_get_mouse_y(gmo.dp);
      if (b == 4 || b == 5) {                       /* wheel → scroll focused */
        int k = (b == 4) ? CACA_KEY_DOWN : CACA_KEY_UP;
        if (app.focus == FOCUS_TREE) gtcaca_tree_key(app.tree, k, NULL);
        else                         gtcaca_table_key(app.table, k, NULL);
      } else if (b == 1) {                          /* left click → focus pane */
        if (my == 1)                         app.focus = FOCUS_FILTER;
        else if (my >= app.tree_y)           app.focus = FOCUS_TREE;
        else if (my >= app.table_y) {
          long row = app.table->top + (my - (app.table_y + 3));
          app.focus = FOCUS_TABLE;
          if (row >= 0 && row < app.nview) app.table->sel = row;
        }
      }
      redraw();
      continue;
    }

    if (!(t & CACA_EVENT_KEY_PRESS)) continue;
    key = caca_get_event_key_ch(&ev);

    /* menu owns input while open */
    if (app.menu->has_focus) {
      if (key == CACA_KEY_ESCAPE) { app.menu->has_focus = 0; app.menu->is_open = 0; }
      else gtcaca_menu_handle_key(app.menu, key);
      redraw();
      continue;
    }

    /* global keys */
    if (key == CACA_KEY_F10) { app.menu->has_focus = 1; app.menu->active_entry = 0; app.menu->is_open = 0; redraw(); continue; }
    if (key == CACA_KEY_F2)  { act_open(NULL); redraw(); continue; }
    if (key == CTRL('q'))    { break; }
    if (key == CTRL('o'))    { act_open(NULL); redraw(); continue; }
    if (key == CTRL('f'))    { act_find(NULL); redraw(); continue; }
    if (key == '\t') {
      app.focus = (app.focus + 1) % 3;
      redraw();
      continue;
    }

    if (app.focus == FOCUS_FILTER) {
      if (key == CACA_KEY_RETURN || key == 10) {
        apply_filter(gtcaca_entry_get_text(app.fentry));
        app.focus = FOCUS_TABLE;
      } else if (key == CACA_KEY_ESCAPE) {
        app.focus = FOCUS_TABLE;
      } else {
        filter_entry_key(key);
      }
      redraw();
      continue;
    }

    /* '/' focuses the filter from a table/tree pane */
    if (key == '/') { app.focus = FOCUS_FILTER; redraw(); continue; }
    /* n / N step through find matches (when a search is active) */
    if (app.find_active && (key == 'n' || key == 'N')) {
      find_jump(key == 'n' ? +1 : -1); redraw(); continue;
    }
    if (key == 'q' || key == 'Q') { break; }

    if (app.focus == FOCUS_TABLE) gtcaca_table_key(app.table, key, NULL);
    else                          gtcaca_tree_key(app.tree, key, NULL);
    redraw();
  }

  caca_set_mouse(gmo.dp, 0);
  detail_clear();
  if (app.filter) filter_free(app.filter);
  capture_free(&app.cap);
  free(app.view);
  caca_free_display(gmo.dp);
  return 0;
}
